### ISSUE TITLE
config show CATEGORY parameter

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#10]
I've begun looking into `config show` command but I'm not finding the info about what should I use as CATEGORY parameter in the help.

**Comment by d5000** [comment]
The categories are: deck, address, proposal, utxo, transaction, checkpoint, donation.

I've added a --categories/-c flag to `config list` to show these categories, for easy access, and added this info to the docstring.

NOTE: I have now reworked this command a bit. An important option (show information of the basic config file) was missing, I've added it. I also changed the order of LABEL_OR_VALUE and CATEGORY to match the scheme used in the `config set` command. LABEL_OR_VALUE now comes "before" CATEGORY. I hope the docstring and error messages are intuitive now.

Commit: 4956be651e8317122f08c0715ae90c0844c1852a

**Comment by buhtignew** [comment]
I think have still some issue to understand the functioning of the `config` group of commands.
For instance I was trying to obtain some meaningful output from `config show` command.
Using the `config list -e` I've got the following list of categories:
```
address
checkpoint
deck
proposal
donation
transaction
utxo
```
While using `config list -e` I've got the following output:
```
address:     {"tslm_origin_address": "mixcqdAy4aFtuBV7uRebqBTjiFWCcS4UEp", "tslm_donor_address7": "mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35", "tslm_donor_address9": "mfq11jH49F2jqUMrVpGZhtyeDC88Vk9Vs8", "tslm_donor_address8": "mg59ZLqztR5zWQB9HknPNHFH4PHwcq4Ee2", "tslm_origin_address7": "mrnrAyYBG9gNzdAiZ6aRDC3tBkrCsjTnSi", "tslm_donor_address6": "n1xC4Dkp48mbsJsMV3yYEho6adBmbjgqNV", "tslm_origin_address4": "n3MtPoPaAREU5GEhAErBPuju83bVog2opz", "tslm_donor_address1.2.1": "mskwPWmHNAV2yfKPDCs4Yt6WvSpfGbA64e", "tslm_donor_address0.2": "n4AoPomtAQRxsTc2TDMFMsP2PonhZ2vVAz", "tslm_donor_address3.2": "mpKx1QBBFSPY3b7CjrR4Mvcq4t1tHiAEcz", "tslm_donor_address1.2": "mzHSKpCYK2J4Np6cVimPQsJufU7ZwesrcL", "tslm_origin_address5": "mjXqewNUxUCW4v6bQ7CzhRAVMLHmQ6ktxN", "tslm_donor_address5": "mq1jZAiu8NoL3U3Ed7YiDdfjmY5t6Zphvq", "tslm_donor_address4": "mrnZpB5Wm1FDBBcZ1s1pdPHpQgzaLRteSr", "tslm_donor_address3": "mfemhfkdD9tZG7Lukv2dT7vdq8d5xYFQCX", "tslm_donor_address1.1": "mhg25VziknSgQLBg6uCMBXsT8VpwbaQUJR", "tslm_donor_address2": "mwgpxrjnzXxfXSdZaD6WvtH1122B1fwMv4", "tslm_donor_address": "mukgdQJzBzCkMVjmUNgcmDJD5cwY3zzua6", "tslm_origin_address2": "mfkwJpC1RaEAPrh6bNk849jFyzMgBA3td1", "tslm_origin_address1": "mxuqE6UWREDuWuMkBWoz1F8jfZur5CM3ZH", "tslm_main": "mw6J8BWwsbERhCmVYPdS4Kk5W21FuK3Qt3", "tslm_new_one": "mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya", "tslm_old_default": "n2nSbZYLV77NFHSD3P4ZdFKyp65rtTHP1b", "tslm_donor_address1": "mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP", "tslm_super_new": "msAzW8dLyCNhnashwThAo2rUNKBycqt7yv", "tslm_test_label": "mgpiP2Dc5QweKFS55HvRqsWyQ6PMXJCVCk", "tslm_keyring_address": "mw9gjLtQVhu34YKep7vrZJDiong69Zmyid", "tslm_second_one": "mjAykGXoJu21VZLr5JymuQXFCXyzhgn3Cb", "tslm_flag-l": "mgUkRF2eosnFQpMKqAYxuzVLxccTPyNxYw", "tslm_no_transactions?": "mqZ5nqs6bpaAqEoEV9jVFfwsM3hBZD4C3J"}
checkpoint:  {"345477": "d738afbf6a5ff6f95f12ca2cce118b9d9125b5ce7b34f92240b356ed54f5b8d2", "345481": "a6432208e2d93ef1ed4823274ab0f51412ba50d8ea5690fd37c1aa6baebfe151", "345483": "9bf821997aa9df84f23aa1e0af75726e2e4b318d5fbde5c0e5598e0833da8caf", "345485": "3a5edbb177b1688d22f3dd03d29142db46f03a94556aebaeeb2cd98f53b65d57", "345486": "c0a69686f45d4bb260d9503bec43f60ab4d5fea735ffe59dbdfe1405fdacef1b"}
deck:        {"PoBtoken": "fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974"}
proposal:    {}
donation:    {}
transaction: {"new": "f4e26f3a14a7fbe7ea45bd60ad9005ebbaa36a3cecd864c7f3ef517c5fe27c86", "second_one": "01000000b317de64010000000000000000000000000000000000000000000000000000000000000000ffffffff0e04b317de640101062f503253482fffffffff01e03caa0600000000232103f0ef2f8702b64da8da1481959a4486b16b94614831e194b2ebfdf8f11c764a85ac00000000", "third_one": "0100000026e2786202b62fcc1263444135f054f431fa8e16468cdc5cf9ab03480e4d3a2341993dd8b3010000006a4730440220258dc6a7483da7f2593f4278da7df2d5ec013b1e51164b4db155b95dba8d93e602202196bda347d2fd7300385dc04e55b8586796f9133956bf36be8bc8fc381d56e8012103103c38266931ffdea961ab58a4be89710953a0e62186856ed7f3f695a1db421effffffff2c5219036db6a6b092f2b5718c88e227195918864dfff48fbb87a4a3bc0daef8010000006b483045022100900a647d8320d1636323317c97be7e12a188ded29e19b182254c94891705a93202201dc6b19f29f3aa1eda8de082561c770c7e0b986af0eb8a5ae19460b082750f19012103103c38266931ffdea961ab58a4be89710953a0e62186856ed7f3f695a1db421effffffff0410270000000000001976a9145fbb9fb88a64bf226051d5797f5db46c3afc710c88ac1027000000000000246a22445342895a6f8aaffbb3e26f776e747c8251ef01d80a6a526bc5199f083f7f4356fa0050d6dc010000001976a914b5a2ced9afd823cb142607e2d4e7e979cb73b87f88acd0549a3b000000001976a914becdce1f2621cd5ad2f8ba27a037fa056d28e6c288ac00000000"}
utxo:        {}
```
So I tried to use the label `new` from `transaction` category to see what output I'd get using `config show new transaction --category --extended`.
I don't know whether the usage was correct on my side, but I've got the following error:
```
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 441, in main
    fire.Fire({
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/extended_classes.py", line 132, in show
    return ei.run_command(self.__show, label_or_value, category=category, extended=extended, label=label, find=find, quiet=quiet)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/extended_interface.py", line 31, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/extended_classes.py", line 157, in __show
    result = ei.run_command(ce.search_value, category, str(label_or_value))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/extended_interface.py", line 31, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/config_extended.py", line 140, in search_value
    raise PacliInputDataError("Category does not exist.")
          ^^^^^^^^^^^^^^^^^^^
NameError: name 'PacliInputDataError' is not defined
```

**Comment by d5000** [comment]
Oh. That's both things, a (very dumb) bug I seem to have produced in one of my last updates of the config command, and an error from your side :)

The correct way to use would have been:
`config show new transaction --extended` (or `-e`)
or:
`config show new --category transaction --extended`.

If you add the `--category` flag the way you did (behind the category name), then it "overrides" the category name you already entered ("transaction"). This means it thinks there is no category entered, and produces this error.

Generally, if you have an option with a value (not a simple Boolean flag), then the value must always been entered after the option, i.e. `--option VALUE`, never `VALUE --option`. The confusion may arise because sometimes the option isn't necessary to enter, like in this case in `config show`.

The bug I mentioned is that normally there should be no traceback shown and a meaningful error message. I've fixed it and uploaded the fix to Github (commit 0cef5e6).

**Comment by buhtignew** [comment]
> If you add the --category flag the way you did (behind the category name), then it "overrides" the category name you already entered ("transaction") with no value, as there is no value behind --category. This means it thinks there is no category entered, and produces this error.

I think I've faced the same issue here with `-c` flag as I did with `-b` flag for `checkpoint set` command initially.
Since it's mentioned in **Flags** I thought it had to be used in [options] position, while actually it's position is before the CATEGORY. 
I think we should add it as optional in the command description where the CATEGORY is mentioned if not its usage is not intuitive at all.

**Comment by d5000** [comment]
Yes, some solution must be found for this problem of "positional arguments which can also be keyword arguments". Let's continue in issue #15 where this problem is discussed in general, there I will document my progress on the issue.

I close here, of course you can reopen if you have a specific issue about this command.
