### ISSUE TITLE
Testnet halted?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#100]
I think that there is something wrong with the testnet right now.
Both my server and my client have 0 connections.
I think that it's possible that my client was banned by the server because I was running the docker's container slimcoinds along with the host's slimcoind and since they all had the same ip, the server(s) has probably considered my ip as misbehaving.
What is the procedure to whitelist an ip?

However the server's slimcoind has 0 connections as well and is halted on the block 440138. Is your server down?

**Comment by d5000** [comment]
This was probably my fault. My provider had maintenance work and thus stopped the slimcoind daemon. I've restarted the server.

Can be closed if everything's ok :)

**Comment by d5000** [comment]
Any node that mines needs at least one connection from my experience. Thus, if my server is down, you can start your local client and should be able to mine with the server as you will have a connection again.

**Comment by buhtignew** [comment]
Thank you for the info, I'm closing this.
