### ISSUE TITLE
How to unban a client?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#106]
Seems like my client is not able to connect to my server. In fact it has only one connection and my local `debug.log` has a line confirms my server is refusing connections from the client.
Do you know the procedure to unban a client?

**Comment by d5000** [comment]
Add bantime=60 to the slimcoin.conf of the server (and perhaps the client too), so the bans will never be longer as 60 seconds. Then restart the server.

**Comment by buhtignew** [comment]
I've set up the bantime as you suggested, but nothing has changed.

The issue should be in something else.

There are the following lines in my local debug.log file:
```
trying connection xx.xx.xxx.xxx:41684 lastseen=-449254.2hrs
connected xx.xx.xxx.xxx:41684
socket recv error 104
disconnecting node xx.xx.xxx.xxx:41684
```
xx.xx.xxx.xxx - is my server's ip

Are you by chance familiar with this kind of messages?

My ufw status is:
```
To                         Action      From
--                         ------      ----
41684/tcp                  ALLOW       Anywhere                  
```

**Comment by d5000** [comment]
Unfortunately this doesn't look familiar to me. It's probably not a ban though. With a ban you would see the message "Connection refused" in debug.log, as far as I remember.

**Comment by buhtignew** [comment]
Ok, I think it makes sense closing this at this point.
