### ISSUE TITLE
token transfers output

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#107]
I've tested `token transfers a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a -a mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn` and got the following output:
```
+Card transfers of deck a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a:--------------------------------+------------------------------------+--------+--------------+
| txid                                                             | confirms | seq | sender                             | receiver                           | amount | type         |
+------------------------------------------------------------------+----------+-----+------------------------------------+------------------------------------+--------+--------------+
| 6b61ba823d9cf5998af8551d19d94c9adc3db38b11f176adced3ff3f2f3757c9 | 4488     | 0   | mtYvCVBtEayA5y6szGSrSgGwHQfe44Bgh2 | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 1.0    | CardTransfer |
| 1c7d88d1d66b1a0e1ebb983d18d71e9af2c8314542e0c2c6d062be40046e7f1b | 4481     | 0   | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 1.0    | CardTransfer |
| 6b61ba823d9cf5998af8551d19d94c9adc3db38b11f176adced3ff3f2f3757c9 | 4488     | 0   | mtYvCVBtEayA5y6szGSrSgGwHQfe44Bgh2 | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 1.0    | CardTransfer |
| 1c7d88d1d66b1a0e1ebb983d18d71e9af2c8314542e0c2c6d062be40046e7f1b | 4481     | 0   | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 1.0    | CardTransfer |
| 6b61ba823d9cf5998af8551d19d94c9adc3db38b11f176adced3ff3f2f3757c9 | 4488     | 0   | mtYvCVBtEayA5y6szGSrSgGwHQfe44Bgh2 | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 1.0    | CardTransfer |
| 1c7d88d1d66b1a0e1ebb983d18d71e9af2c8314542e0c2c6d062be40046e7f1b | 4481     | 0   | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 1.0    | CardTransfer |
+------------------------------------------------------------------+----------+-----+------------------------------------+------------------------------------+--------+--------------+
```
My `address list | grep mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn` output is 
```
|                      | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 0.09         | 0          | 1.0         |
```
So it contains just one dPoD token while from the above `token transfers` output it seems like it has received 6 of them. Maybe the `token transfers` command doesn't show the outgoing transactions of an address?
However it seems like in this case the same transactions has been listed 3 times each.

I've checked the `token transfers a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a` output and it seems like there are other transactions mentioned more than once:
```
 txid                                                             |confirms |seq| sender                             | receiver                           | amount  | type         
 0064a21776ddf70004d34c7a51de68de585e7ee6b5e0d5d4d43832984892077c |313109   |0  | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh |51.37    | CardIssue    
 0064a21776ddf70004d34c7a51de68de585e7ee6b5e0d5d4d43832984892077c |313109   |0  | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh |51.37    | CardIssue    
 0064a21776ddf70004d34c7a51de68de585e7ee6b5e0d5d4d43832984892077c |313109   |0  | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh |51.37    | CardIssue    
 0064a21776ddf70004d34c7a51de68de585e7ee6b5e0d5d4d43832984892077c |313109   |0  | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh |51.37    | CardIssue    
 0064a21776ddf70004d34c7a51de68de585e7ee6b5e0d5d4d43832984892077c |313109   |0  | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh |51.37    | CardIssue    
 1c7d88d1d66b1a0e1ebb983d18d71e9af2c8314542e0c2c6d062be40046e7f1b |4481     |0  | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn |1        | CardTransfer 
 1c7d88d1d66b1a0e1ebb983d18d71e9af2c8314542e0c2c6d062be40046e7f1b |4481     |0  | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn |1        | CardTransfer 
 1c7d88d1d66b1a0e1ebb983d18d71e9af2c8314542e0c2c6d062be40046e7f1b |4481     |0  | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn |1        | CardTransfer 
 61a801801d7b6d5d683371616d9eab6578801c931cd43ce18390ee5c4fb1a1ae |1389     |0  | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mzP9BNtqjSNq2rJ58w8GpQNnez38NGagsU |1        | CardTransfer 
 6b61ba823d9cf5998af8551d19d94c9adc3db38b11f176adced3ff3f2f3757c9 |4488     |0  | mtYvCVBtEayA5y6szGSrSgGwHQfe44Bgh2 | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn |1        | CardTransfer 
 6b61ba823d9cf5998af8551d19d94c9adc3db38b11f176adced3ff3f2f3757c9 |4488     |0  | mtYvCVBtEayA5y6szGSrSgGwHQfe44Bgh2 | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn |1        | CardTransfer 
 6b61ba823d9cf5998af8551d19d94c9adc3db38b11f176adced3ff3f2f3757c9 |4488     |0  | mtYvCVBtEayA5y6szGSrSgGwHQfe44Bgh2 | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn |1        | CardTransfer 
 b8bd6efd07ced0994fdfffbd11a5bfc8d8db3d9b0ae35d0eb81f6443bb4a7dea |22525    |0  | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya |10       | CardTransfer 
 b8bd6efd07ced0994fdfffbd11a5bfc8d8db3d9b0ae35d0eb81f6443bb4a7dea |22525    |0  | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya |10       | CardTransfer 
 b8bd6efd07ced0994fdfffbd11a5bfc8d8db3d9b0ae35d0eb81f6443bb4a7dea |22525    |0  | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya |10       | CardTransfer 
 b8bd6efd07ced0994fdfffbd11a5bfc8d8db3d9b0ae35d0eb81f6443bb4a7dea |22525    |0  | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya |10       | CardTransfer 
 f8045efacdffe7ac25361d1593b40f7890efbe922b043a9c17a98c1e0579e827 |2433     |0  | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mtMGkB2mVxzPNZCWHruRmG1SmsSJBtyCUD |1        | CardTransfer 
 f8045efacdffe7ac25361d1593b40f7890efbe922b043a9c17a98c1e0579e827 |2433     |0  | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mtMGkB2mVxzPNZCWHruRmG1SmsSJBtyCUD |1        | CardTransfer 
```

UPDATE 
I've checked `token transfers fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974` output and it seems like the same transaction are not listed more than once.

UPDATE1:
I've checked all the other deck's I've initialized that has anything in their `token transfers` output, i.e. `63402dbbeb280d41701f2a23caac226e938ff354daec0ff8bd7903ac59696284`, `e9c2c5bdfdd46372111ec29bf8f30ae39177cf1042ff94b6911e53048c78c0c5`, `e9c2c5bdfdd46372111ec29bf8f30ae39177cf1042ff94b6911e53048c78c0c5`, `3369f3eb703656c0b46b613dcfb4df78fc05657a0b75f44551634de6321d9d9c`, `95b24015ffb46d82015b709d774542fc4a53ccf27f72d973ed3fb18c384a80ca` and `7a2ae406ddf44ddb17532d4888fdc14573f52749445e9e014075c9f83cbe556f`

and have  discovered that only `3369f3eb703656c0b46b613dcfb4df78fc05657a0b75f44551634de6321d9d9c` has the same transfers mentioned more than once:
```
| 0080ba9364e2446f0eb81e157505807ec918012068c0dfe0ef1b829bc6baf85c | 309699   | 0   | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | 3.42   | CardIssue    |
| 0080ba9364e2446f0eb81e157505807ec918012068c0dfe0ef1b829bc6baf85c | 309699   | 0   | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | 3.42   | CardIssue    |
| f36bb4c8afe984e4954209eedfd1355015d35f72113ada605e3c64ee53082c14 | 309252   | 0   | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | 34.59  | CardIssue    |
| 0080ba9364e2446f0eb81e157505807ec918012068c0dfe0ef1b829bc6baf85c | 309699   | 0   | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | 3.42   | CardIssue    |
| f36bb4c8afe984e4954209eedfd1355015d35f72113ada605e3c64ee53082c14 | 309252   | 0   | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | 34.59  | CardIssue    |
| 8ff3acb811df73b1126dfa4f1b00e697c9c4d8bb6771a6109822d81f39a32f48 | 174988   | 0   | mmBwLVyqZWuUDuTpmmpzBvT41azKBevZhh | mtFXZtZKndW47L99JooLy42UBXHCwNLvPF | 5.0    | CardTransfer |
```

I've also discovered that there are some decks that have CardTransfers, but none CardIssue type of transfers, for instance `e9c2c5bdfdd46372111ec29bf8f30ae39177cf1042ff94b6911e53048c78c0c5` and `63402dbbeb280d41701f2a23caac226e938ff354daec0ff8bd7903ac59696284`. Is it expected?

**Comment by d5000** [comment]
Yes I've seen these duplicates too. They look familiar to me as we had last year a similar issue with PoB tokens, probably it affects dPoD tokens too but was only solved for AT/PoB. Will investigate.

fb93... is a PoB token, so this would indicate that it is indeed solved for PoB but not for dPoD.

> Maybe the token transfers command doesn't show the outgoing transactions of an address?

The new `-a` option was implemented in a way that the address is taken into account as sender and receiver, i.e. it should show incoming and outgoing transfers from that address.

However, if we strip the duplicates problem, then there remains an inconsistency: you should have 2 tokens on that address (mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn) and not only one. 

> I've also discovered that there are some decks that have CardTransfers, but none CardIssue type of transfers, for instance e9c2c5bdfdd46372111ec29bf8f30ae39177cf1042ff94b6911e53048c78c0c5 and 63402dbbeb280d41701f2a23caac226e938ff354daec0ff8bd7903ac59696284. Is it expected?

These are probably the old dPoD tokens where the issues aren't valid anymore. With the `-v` option you can check if the transfers are valid. I'm considering to make this option active by default as most users would be probably only interested in the valid transfers.

**Comment by d5000** [comment]
Fixed. This was a pypeerassets bug, so please upgrade. pypeerassets commit is 6c51e85.

**Comment by buhtignew** [comment]
> Fixed. This was a pypeerassets bug, so please upgrade. pypeerassets commit is 6c51e85.

The fix has worked on my side.

>> So it contains just one dPoD token while from the above token transfers output it seems like it has received 6 of them.

> One of both transactions is invalid, that's the reason one token only is shown and not two.

The duplicate has gone away so my `token transfers a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a -a mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn` output is:
```
+Card transfers of deck a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a:--------------------------------+------------------------------------+--------+--------------+
| txid                                                             | confirms | seq | sender                             | receiver                           | amount | type         |
+------------------------------------------------------------------+----------+-----+------------------------------------+------------------------------------+--------+--------------+
| 6b61ba823d9cf5998af8551d19d94c9adc3db38b11f176adced3ff3f2f3757c9 | 13138    | 0   | mtYvCVBtEayA5y6szGSrSgGwHQfe44Bgh2 | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 1.0    | CardTransfer |
| 1c7d88d1d66b1a0e1ebb983d18d71e9af2c8314542e0c2c6d062be40046e7f1b | 13131    | 0   | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 1.0    | CardTransfer |
+------------------------------------------------------------------+----------+-----+------------------------------------+------------------------------------+--------+--------------+
```
While my `address list | grep mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn` is:
```
|                      | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 0.08         | 0          | 1.0         |
```
So as from your feedback one of the above transactions is not valid.
Would it be possible/make sense to let it immediately clear somehow from the `token transfers a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a -a mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn` output?
For instance something like this
```
+Card transfers of deck a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a:--------------------------------+------------------------------------+--------+--------------+
| txid                                                             | confirms | seq | sender                             | receiver                           | amount | type         |
+------------------------------------------------------------------+----------+-----+------------------------------------+------------------------------------+--------+--------------+
| 6b61ba823d9cf5998af8551d19d94c9adc3db38b11f176adced3ff3f2f3757c9 | 13138    | 0   | mtYvCVBtEayA5y6szGSrSgGwHQfe44Bgh2 | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 1.0    | CardTransfer |
| 1c7d88d1d66b1a0e1ebb983d18d71e9af2c8314542e0c2c6d062be40046e7f1b | 13131    | 0   | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | ~1.0~    | CardTransfer |
+------------------------------------------------------------------+----------+-----+------------------------------------+------------------------------------+--------+--------------+
```

**Comment by d5000** [comment]
It's much easier to implement, and I think also more intuitive, to make the `-v` option standard. So you see in the standard view only the valid transactions. Only in compatibility mode this option would be set to False then. This is something I had always planned but forgot to implement.

I have implemented it now this way and the `-s / --show_invalid` option has been added to allow the original view (with invalid transactions) in standard mode. `-v` is now only necessary if compatibility mode is on. I added also `-o / --only_invalid` as a debugging option only showing invalid transfers.

Commit: b35fbc1

**Comment by buhtignew** [comment]
> I have implemented it now this way and the -s / --show_invalid option has been added to allow the original view (with invalid transactions) in standard mode.
This works.
_
I don't know whether it's relevant but by running
- `token transfers a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a -a mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn -o`
- `token transfers  a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a  -a mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn -v FALSE`
- `token transfers  a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a  -a mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn -v TRUE`
and 
- `token transfers  a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a  -a mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn`, `token transfers  a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a  -a mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn -v TRUE` and `token transfers  a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a  -a mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn -v FALSE` both after I've run `config set TRUE -c` and `config set FALSE -c` the output I'm getting is always:
```
+Card transfers of deck a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a:--------------------------------+------------------------------------+--------+--------------+
| txid                                                             | confirms | seq | sender                             | receiver                           | amount | type         |
+------------------------------------------------------------------+----------+-----+------------------------------------+------------------------------------+--------+--------------+
| 1c7d88d1d66b1a0e1ebb983d18d71e9af2c8314542e0c2c6d062be40046e7f1b | 31236    | 0   | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn | 1.0    | CardTransfer |
+------------------------------------------------------------------+----------+-----+------------------------------------+------------------------------------+--------+--------------+
```

**Comment by d5000** [comment]
Again, do not use all capitalized for compatibility mode, use True/False, not TRUE/FALSE.
