### ISSUE TITLE
Hidden labels

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#112]
I've tested `token set johntok1 7984c5d710862fb624a9b1f3678fe277f62d25590ff71158a9dfa1556650560a` and got the following message:
```
Error: Value already exists, you can't change it in protected mode
```
Then I've run `token set abcd 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be` and was able to create and then to delete the label.
Then I've run the same command again and tried to modify the label by running `token set abcd1 abcd`, which of course was a wrong command, and got:
```
Stored deck:
Label: abcd1
Value: abcd
```
while the label in my `token list | grep 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be` output has of course not changed:
```
| abcd                  | 66c25ad60538a9de0a7895d833a4a3aeeacdd75b1db9c5dd69c3746dd21d39be | PoBTokenLimited2          | mvrm2HAoKqiCmeQiwKMuEFpeEn7rJEmpMz | 1 | 319946 |   |
```
However there was no `abcd` deck_ID in my `token list` output either.

Then I've run `token set abcd1 abcd` again and got:
```
Error: Value already exists, you can't change it in protected mode.
```
At this point I've realized to have used the wrong command and have remembered about the hidden labels we've already discussed in the past.

I've run `token set abcd -d -n`, `token set abcd1 -d -n` and `token set johntok1 -d -n` and was able to use all the labels without any issue again.

What I've got from this experience is that 
1) we actually have deck's hidden labels that are not visible in the `token list` output, only in the `config list -e`. 
2) it's possible to store a label for a deck that doesn't exist and both the label and the wrong deck_id are stored as labels somewhere.

With the transaction and address labels the situation is different: the additional labels are visible in the `transaction list`/`address list` output and each address/transaction is basically listed more then once if there are more than one label associated with it.

For the transactions it's not possible to set a label for an invalid transaction (at least I was not able to find the way to), but for the addresses the invalid address can be labeled and it produces error in the next `address list` run (the issue is described in #116).

So for the decks I'd suggest us to consider one of the three possible improvements:

1st solution:
1) When the `token set [something_here] [something_here]` command is run the last argument is being checked against existent decks, if there are none an error message is thrown and nothing happens.
2) If the last argument is an existent deck we check whether a label for that deck is already set and if so and error is thrown.

2d solution:
1) When the `token set [something_here1] [something_here2]` command is run the last argument is being checked not only against the existent decks but also against the existent labels. If none is found the error is thrown, if the label is found it's being modified with the new one (i.e. with the `[something_here1]` argument).
2) If the last argument is an existent deck we check whether a label is already set for that deck and if so we modify the old label with the new one. 
This solution would make the `-m` flag obsolete.

3rd solution:
1) Checking the assumed deck_id argument against existing decks.
2) Let the `token list` command output the same deck_id more than once, one entry for each existent label.

The points 2 of the first and the second solutions may also be applied to the `address set` command (I'd suggest us to adopt the same solution both for the `address set` as for `token/deck set` commands, but I'm not sure we should consider to create any uniformity with the `transaction set` command in this case.)
In this way we'd get rid of the hidden labels.

**Comment by d5000** [comment]
Fixed as of commit 8bf74f0. Both decks and addresses are now checked for validity (not for "existence").

**Comment by buhtignew** [comment]
And what about "hidden" labels for decks? 

I think it's possible that a user accidentally (or also on purpose) sets a different label twice for the same deck and the second one wouldn't be visible in the `token list` output, thus he'd try to set it again receiving `Error: Value already exists, you can't change it in protected mode.` that may be difficult for him to understand without knowing the new label is stored along the old one and is visible with `config list -e`.

I'd also like to know what do you think about suppressing the `-m` flag as per solution 2 above, because the usage `token set [new_label] [old_label]` seems to me quite intuitive.

If solution 2 would requires too much work, I think we should at least add the decks multiple times in the `token list` output if there are multiple labels as it already works for the addresses and transactions.

**Comment by d5000** [comment]
I have changed the command now so that all labels are shown. A blank line (below the deck's main data row) is shown for the duplicate labels.

I don't consider removing `-m` due to consistency reasons.

**Comment by buhtignew** [comment]
> I have changed the command now so that all labels are shown. A blank line (below the deck's main data row) is shown for the duplicate labels.

It doesn't look intuitive to me which deck the blank line is referring to (whether the previous one or the next one) and also it's not in line with how we are managing the multiple labels outputs for labeled addresses and transactions. 
What if we just list the same info multiple times if there are multiple labels as we do it in other cases?

**Comment by d5000** [comment]
Nope. This is a completely niche thing and I'll not waste any resources on it.
