### ISSUE TITLE
-r flag in config set command in compatibility mode

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#119]
There is the following line in the `config set` help:
```
(NOTE: In compatibility mode, the -r flag can be omitted.)
```
I've tried to omit the flag after I've run both `config set TRUE -c` and `config set FALSE -c`, but it was not possible use `config set LABEL VALUE` without the `-r` flag both for the extended as for basic configuration file.

So I think we should either exclude that line from the `config set` help or implement the mentioned functionality.

**Comment by d5000** [comment]
I now clarified in the help that omitting -r works only for the basic configuration file when compatibility mode is set to True. 

This works here (I've tested it with the "production" setting, i.e. `config set production False` and then back to True) as this does not throw the ConnectionError afterwards.

You mentioned that this didn't work in a case with the basic file, which configuration was it exactly?

**Comment by d5000** [comment]
It seems the compatibility mode setting only understands **True** (only first letter capitalized) and not **TRUE** (all capitalized). When I do `config set TRUE -c` it sets the compatibility mode to _False_ (which is also shown in the message). This is obviously the problem in your case.

I've looked into the help and there is no wording suggesting you should use all-capitalized. So I think this can be closed.

**Comment by buhtignew** [comment]
The issue was indeed the capitalization, I'm closing this issue.
