### ISSUE TITLE
0.05 of transaction fee?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#121]
I've run `slimcoind sendtoaddress mie75nFHrNAHHKfQ141fWfWozdMnaec8mb 1` and which has created transaction `b1d958b5dc97c4b3d954c8da4a0af3cc9cbc9f0f24706c723103e3de5117ffe8`.
Then I've had a look into the `transaction show b1d958b5dc97c4b3d954c8da4a0af3cc9cbc9f0f24706c723103e3de5117ffe8 -s` output and have seen the following:
```
{
    'inputs': [
        {'sender': ['mk9WFSTqgtTJbwb5g6pGpByTRbYKiSaX3w'], 'value': 0.96},
        {'sender': ['mz6HENDiSFPYqsi7wDZ33p5jt7j9LFo6qr'], 'value': 0.01},
        {'sender': ['mzP9BNtqjSNq2rJ58w8GpQNnez38NGagsU'], 'value': 0.01},
        {'sender': ['n4UW9h3QvBRxdF9prmT8cP8p13Vm8VYJn9'], 'value': 0.01},
        {'sender': ['mtMGkB2mVxzPNZCWHruRmG1SmsSJBtyCUD'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn'], 'value': 0.01},
        {'sender': ['mxuqE6UWREDuWuMkBWoz1F8jfZur5CM3ZH'], 'value': 0.01},
        {'sender': ['mwutmXuJEzDvfs59nKY47Unm3M8cszxhf9'], 'value': 0.01},
        {'sender': ['mtMGkB2mVxzPNZCWHruRmG1SmsSJBtyCUD'], 'value': 0.01},
        {'sender': ['mxTq1JuXLMZjaKA8LkdySk3sMwhRz4FEG2'], 'value': 0.01}
    ],
    'outputs': [
        {'receivers': ['my3CiW1Zqh5ENA9AXUnjG6k1Rup23JfcCo'], 'value': 0.01},
        {'receivers': ['mie75nFHrNAHHKfQ141fWfWozdMnaec8mb'], 'value': 1.0}
    ],
    'blockheight': 'unconfirmed'
}
```
The difference between value that was sent and the value that was received seems to be 0.05 does it mean that the transaction's fee was 0.05 tSLMs this time?

**Comment by d5000** [comment]
This transaction has 3.4 kB. 0.01 rate is per kB in Peercoin-based coins. So "normally" it should have 0.04 tx fees. I can't explain the 0.01 additional fee, maybe Slimcoin client is sometimes too generous. Number of inputs and output is also ok.
