### ISSUE TITLE
address list with -a -k flag

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#124]
I've tested `address list -a -k` and I think that the output was as expected.
The peculiarity I've noticed is that there was no 
```
/usr/lib/python3.12/functools.py:58: ResourceWarning: unclosed <socket.socket fd=8, family=1, type=1, proto=0, raddr=/run/user/1000/bus>
  getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
``` 
message we've discussed many times in the past, which makes me think it's being suppressed or the issue is already solved somehow for that command.

**Comment by d5000** [comment]
Indeed I don't get it with `-a` but without it I get the message. Closing.
