### ISSUE TITLE
Wish list for the version 2

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#129]
As suggested by you [here](https://github.com/slimcoin-project/pacli/issues/112#issuecomment-2156177288) some of the features that may be desirable from my point of view are not that urgent from your point of view as now.
So I've thought to create a wish list in order to keep track of the features to possibly implement in the next version(s).
If something I've put here can be improved or replaced with a better solution, please reply so I'll change the wish list.
Of course you are welcome to add features in the wish list if you want.

Here are the improvements I'd like us to consider:
- I'd like us to substitute the blank lines in the `token list` output in case of the multiple labels with the full information about the deck to keep the `token list`, `transaction list` and `address list` outputs consistent in case of multiple labels (see the issue #112).
- I'd like us to find the way to solve the message
```
/usr/lib/python3.12/functools.py:58: ResourceWarning: unclosed <socket.socket fd=8, family=1, type=1, proto=0, raddr=/run/user/1000/bus>
  getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
``` 
when using the `address list -k` command, since it seems like it's already hidden/solved in case of `address list -a -k` output, for instance (see the issue #124).
- By implementing the courtesy message for the `-w` flag used with the `address list` command we've broken the principle we've been following so far (if I've got it right) to just ignore the wrong combination of flags. If we decide to keep that message I'd like us to introduce it for the `-o` flag in the same command as well and to make it a little be more gentle, i.e. something like "please check the flag usage running address list -h command" instead of "read the help" (see the issue #122).

**Comment by d5000** [comment]
This should go into the wiki, not here. And I probably will not be available for this version.

**Comment by buhtignew** [comment]
> This should go into the wiki, not here.

We don't have a pacli wiki. How should I behave in this case? Should I create it the pacli repository or in slimcoin's one where we are keeping all the documentation for the moment?

> And I probably will not be available for this version.

I don't think I'll go on with this project without you.

**Comment by d5000** [comment]
I have created a Pacli wiki and a [Feature Request](https://github.com/slimcoin-project/pacli/wiki/Feature_Request) page on the Pacli wiki. There probably needs to be some formatting work.

I only want to say that I will not accept any kind of pressure to add any feature _myself_. If there is time for additions I consider not of particular importance, then there is time, if not, there is not. But if some other developer wants to add any feature without affecting the current feature set, everybody is free to do so and submit a pull request.

I'll close this in a couple of days.

**Comment by buhtignew** [comment]
I think this can be closed.
