### ISSUE TITLE
config update_extended_categories

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#13]
I've run both `config update_extended_categories` and `config update_extended_categories -d` but got no output.

I assume everything went smoothly, but I don't really know what and how.

Maybe we should add some message as output?

**Comment by d5000** [comment]
I added a message when the categories are not changed. It is shown by default now, and it is also shown if a new category is added. Also, I added a `--quiet` flag and instead deleted the `--debug` flag. It's not really debug information what is shown, so by default the command can be a little bit more verbose.

**Comment by buhtignew** [comment]
Great, I've tested it and it works.
So the extended categories are being downloaded from somewhere to be up to date?

**Comment by d5000** [comment]
Not exactly "downloaded". The categories are determined in a constant in the Python (CATEGORIES in config_extended.py)  code. If we decide to add a new category to this constant and thus update the code, with this command the user can  update the JSON structure in their extended config file.

I guess this command will be used very seldomly, and if an important category change is made "in production", i.e. when the token was launched and people are using the software really, then I will think about ways to update the categories automatically.

I think we can close this issue, can't we? (if you have a question simply reopen it)
