### ISSUE TITLE
A question about the integrity test

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#134]
I have some command testing on standby because you've told me [here](https://github.com/slimcoin-project/pacli/issues/86#issuecomment-2118623387) to wait.
I'm conscious about [the next your post in the same thread](https://github.com/slimcoin-project/pacli/issues/86#issuecomment-2156211581) were you've told the issue were solved, but to be sure I'd like to ask you whether the issues with the integrity test you've mentioned there (and also [here](https://github.com/slimcoin-project/pacli/issues/50#issuecomment-2019341601)) would still affect the locator related commands or if I can go on with testing them.
Specifically I'm having the following commands testing in standby right now: `token cache`, `token init`, `address cache`.

**Comment by d5000** [comment]
These commands can all be tested, the problem is with the integrity test code itself.

**Comment by buhtignew** [comment]
Thank you for your reply.
I'm closing this.
