### ISSUE TITLE
transaction set_utxo

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#136]
I've re-checked `transaction set_utxo` command. Seems like something has changed in its logic since I've used it [here](https://github.com/slimcoin-project/pacli/issues/3#issue-2085698721)
I've tried `transaction set_utxo trx_label 00fd9b41a42cd8c9c78ea20d1e3a466de07147e4c1ff0119608239c0583ada5d` and got the following error message:
```
 File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 479, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 1833, in set_utxo
    utxo = "{}:{}".format(txid_or_oldlabel, str(output))
                                                ^^^^^^
NameError: name 'output' is not defined. Did you mean: 'outut'?
```

I've also tried `transaction set_utxo trx_label 00fd9b41a42cd8c9c78ea20d1e3a466de07147e4c1ff0119608239c0583ada5d  0`, `transaction set_utxo trx_label 00fd9b41a42cd8c9c78ea20d1e3a466de07147e4c1ff0119608239c0583ada5d 1` and `transaction set_utxo trx_label 00fd9b41a42cd8c9c78ea20d1e3a466de07147e4c1ff0119608239c0583ada5d  2` (since I don't know how to retrieve the output data for this transaction) but got the same error message.

UPDATE:
I've taken a transaction from the `token transfers fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974` output and have run `transaction set_utxo trx_label bc8c92dfe02b6c9ed53c0add55a347318d7eba6a8cde138e386f1859763be6bc 0` thinking that the required Output data is what is called in the `token transfers` output with the abbreviation "seq", but the error message hasn't gone. 

I've also tried `transaction set_utxo trx_label bc8c92dfe02b6c9ed53c0add55a347318d7eba6a8cde138e386f1859763be6bc None` with the same result.

**Comment by d5000** [comment]
Fixed in commit caa0a91. Was a simple typo in my last modification of this command, where I didn't change the logic but changed the flag names to allow one-letter flags.

I added a check to ensure the user adds the output.
If everything works for you it can be closed. Here everything works now.
