### ISSUE TITLE
transaction list --all with date instead of block height

### ISSUE THREAD

**Issue by d5000** [slimcoin-project/pacli#14]
I've implemented what I wrote in the transaction list thread:

`transaction list --all` (the variant which cycles through blocks to find non-wallet transactions) can now also be used using a date to select the start and end block, instead of block heights.

Syntax is:

`transaction list --all --start=YYYY-MM-DD --end=YYYY-MM-DD`

The command tries to find always the first block of the start date and the last block of the end date. Timezone is always UTC.

Dates can be also combined with blocks, e.g. `transaction list --all --start=2024-01-15 --end=322000` (this is a combination which should only take some seconds or at most few minutes)

Testing of this variant can be done in this thread - if there's everything ok and there are no further questions it can be closed.

**Comment by d5000** [comment]
About caching of results of "block scans":

I've planned that as a long term feature. If made well, everybody can have a relatively fast block explorer with its node. Users could for example define that they're interested only from a certain block height on (for example when they joined Slimcoin) and then they could run a scan once and then they only have to catch up (similar what the XMR client Feather does).

Doing it "the right way" would however mean to add a database, which would consume lots of development time.

I can however implement a "quick and dirty" feature: storing the  block transactions in text files, for example in JSON format, similar to the extended config file (but of course in another file). This would be ok for testnet tests, but for millions of blocks it would not be a good solution.

If you think it's important for you to test, I'll do the latter, as this should not consume me more than an hour or two.

**Comment by buhtignew** [comment]
I wouldn't like to make you losing your time with the feature that is not urgent.

I'd like to try working with the blockheights and date rages before.

Right now I've tested `transaction list --all --start='2023-11-01'` and got the following output:
```
        Error raised by PeerAssets.

        Probably the deck you specified didn't exist, or you need to initialize a deck.

        To initialize the default decks, use:

        pacli deck init

        To initialize a single deck, use:

        pacli deck init DECKID [--podtoken]
```
Which decks should be initialized for us to go on with testing comfortably?

**Comment by d5000** [comment]
Thank you for testing. Unfortunately I couldn't reproduce the error.

Due to the other bug with transaction list, I fired up a node with the wallet you sent me, but unfortunately it also didn't show this error.

1) Did this error appear instantly, or was the command running for a long while until this error got thrown? This could indicate, for example, that a memory error happened due to this command consuming much memory when used for long stretches of blocks, and the stretch from November 2023 could have been long enough.

2) If the error appeared instantly or after a short time, could you run the same command with `--debug` flag? This should give a traceback at the end.

**Comment by buhtignew** [comment]
Strange thing, but now it works....

**Comment by buhtignew** [comment]
I've tested `transaction list --all --start=353126` and the scanning has begun from the block 0.

**Comment by d5000** [comment]
>  I've tested transaction list --all --start='2024-02-14' and the output is stuck on

Yes, this was a bug, thanks. Future dates now raise an error.

>  I've tested transaction list --all --start=353126 and the scanning has begun from the block 0.

I can't reproduce that, I think you meant that the ending block was shown with 0. I've changed that misleading message, and introduced some checks to prevent that future blocks and/or start blockheights larger than end blockheights are entered.

Fixes were applied in commit d327046.

About the number of transactions: I think this are simply the mining transactions of your server (almost 1000/day) and perhaps some PoS/PoB minting txes. I did not transact myself in the last days at all, afaik (at least not actively).

**Comment by buhtignew** [comment]
>> I've tested transaction list --all --start=353126 and the scanning has begun from the block 0.

> I can't reproduce that, I think you meant that the ending block was shown with 0. I've changed that misleading message, and introduced some checks to prevent that future blocks and/or start blockheights larger than end blockheights are entered.

Fixes were applied in commit https://github.com/slimcoin-project/pacli/commit/d3270462189d428f383177c7af2d208bdf882f50.

The issue on my side was that in case of `--start=[blocknumber]` flag the `transaction list --all` command was not only outputting the last block as 0, but also beginning to scan from the block 0.
However your fix has solved my issue as well.

> About the number of transactions: I think this are simply the mining transactions of your server (almost 1000/day) and perhaps some PoS/PoB minting txes. 

Oh, my. Of course it's the rewards for the burning transactions I did in the past!

>>  I've tested transaction list --all --start='2024-02-14' and the output is stuck on

> Yes, this was a bug, thanks. Future dates now raise an error.

I've just tested `transaction list --all --start='2024-02-18'` and got the following output:
```
Searching transactions (this can take several minutes) ...
Starting at block: 354852
Ending at block: 354853
{
    'txid': 'a7a6e0ac5877665f3dbb78c1d2c868a3a6f334dff445419e9ae7c10748f8816c',
    'inputs': [
        {'sender': ['mn3SEFsbsb5jw91q7GopWURMw6Hhzg6iF6'], 'value': 6.022286}
    ],
    'outputs': [
        {'receivers': [], 'value': 0.0},
        {'receivers': ['mn3SEFsbsb5jw91q7GopWURMw6Hhzg6iF6'], 'value': 3.06},
        {'receivers': ['mn3SEFsbsb5jw91q7GopWURMw6Hhzg6iF6'], 'value': 3.07098}
    ],
    'blockheight': 354852
}
{
    'txid': '7f170e7f2065073d134ce1f3d8949f22e7382f0ea8289a383982306c53c54291',
    'inputs': [
        {'sender': ['mn3SEFsbsb5jw91q7GopWURMw6Hhzg6iF6'], 'value': 5.23}
    ],
    'outputs': [
        {'receivers': [], 'value': 0.0},
        {
            'receivers': ['mn3SEFsbsb5jw91q7GopWURMw6Hhzg6iF6'],
            'value': 5.996887
        }
    ],
    'blockheight': 354853
}
```

**Comment by buhtignew** [comment]
> I've just tested transaction list --all --start='2024-02-18' and got the following output

The error message is correct now.
I think this issue should be closed.
