### ISSUE TITLE
pobtoken claim with multiple receivers

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#145]
I've tested  `pobtoken claim ATTokenNewSpec2_local  f7d94d3391230e997c0120cab4ea6a8e02fe06408ddd0adc1fc1c4a9d70ed08c -r [mwvsHNwNQ8eiRFGHNqnpD7EdoFk5zzAdYH, mnYTcGF8vVuSAYeoxxNaFWX94QUFM92YZf, mk9WFSTqgtTJbwb5g6pGpByTRbYKiSaX3w, n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL] -a [1, 2, 3, 4]` and `pobtoken claim ATTokenNewSpec2_local  f7d94d3391230e997c0120cab4ea6a8e02fe06408ddd0adc1fc1c4a9d70ed08c -r "[mwvsHNwNQ8eiRFGHNqnpD7EdoFk5zzAdYH, mnYTcGF8vVuSAYeoxxNaFWX94QUFM92YZf, mk9WFSTqgtTJbwb5g6pGpByTRbYKiSaX3w, n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL]" -a [1, 2, 3, 4]` and got:
```
 File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 479, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/at_classes.py", line 129, in claim
    payto = ec.process_address(payto)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_commands.py", line 105, in process_address
    raise ei.PacliInputDataError("No valid address string or non-existing label in the {}.".format(msg_keyring))
pacli.extended_interface.PacliInputDataError: No valid address string or non-existing label in the extended configuration file.
```
~~Then I've also tried~~<code><s> pobtoken claim ATTokenNewSpec2_local  f7d94d3391230e997c0120cab4ea6a8e02fe06408ddd0adc1fc1c4a9d70ed08c -r "[mwvsHNwNQ8eiRFGHNqnpD7EdoFk5zzAdYH, mnYTcGF8vVuSAYeoxxNaFWX94QUFM92YZf, mk9WFSTqgtTJbwb5g6pGpByTRbYKiSaX3w, n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL]" -a "[1, 2, 3, 4]" </s></code>~~and got:~~
<pre>
<s>Error: Amount of cards does not correspond to the spent coins. Use --force to override</s>
</pre>
~~What am I doing wrong here?~~
_
Update 23-07-2024
Today I've understood that if the brackets are put into quotes both for the list of receivers addresses (like this, for instance: `"[mwvsHNwNQ8eiRFGHNqnpD7EdoFk5zzAdYH, mnYTcGF8vVuSAYeoxxNaFWX94QUFM92YZf, mk9WFSTqgtTJbwb5g6pGpByTRbYKiSaX3w, n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL]"`) as for the list of amounts (`"[100, 30, 3, 1]"`) and the sum of amounts corresponds to the whole amount to claim the command runs smoothly. 
Maybe it worth mentioning both info in the `pobtoken claim` help.

Another condition I've just discovered is that any amount in the amounts' list can't be zero.

**Comment by d5000** [comment]
I've mentioned the issue with the quotes in the help, so I'm closing.
I think that no zero is allowed should be obvious, it would make no sense.
