### ISSUE TITLE
pobtoken claim with the -f flag

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#147]
I've tried to run `pobtoken claim ATTokenNewSpec2_local  ac4bac1d215477895f259312ebfa5469bd1f8cf854a8345f8c91249f7676abcd --payto n3MtPoPaAREU5GEhAErBPuju83bVog2opz --payamount 100000000 -f` and got the following error message:
```
Error: Claimed amount 100000000 higher than available amount 500.0.
```
So it has become clear to me that the `-f` is not there to force the system to release amounts higher than the due ones :-) 

Later on I've been re-testing the `pobtoken claim` for the multiple receivers and since by running `pobtoken claim ATTokenNewSpec2_local  d8d9c1253fd7e68a9f7b66c48e0a7de45b6469e2a4f93af803d40d9db0c5845c -r "[mwvsHNwNQ8eiRFGHNqnpD7EdoFk5zzAdYH, mnYTcGF8vVuSAYeoxxNaFWX94QUFM92YZf, mk9WFSTqgtTJbwb5g6pGpByTRbYKiSaX3w, n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL]" -a "[0.1, 0.2, 0.3, 0.4]"` I've got
```
Error: Amount of cards does not correspond to the spent coins. Use --force to override.
``` 
I've tried `pobtoken claim ATTokenNewSpec2_local  d8d9c1253fd7e68a9f7b66c48e0a7de45b6469e2a4f93af803d40d9db0c5845c -r "[mwvsHNwNQ8eiRFGHNqnpD7EdoFk5zzAdYH, mnYTcGF8vVuSAYeoxxNaFWX94QUFM92YZf, mk9WFSTqgtTJbwb5g6pGpByTRbYKiSaX3w, n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL]" -a "[0.1, 0.2, 0.3, 0.4]" -f` and have produced the transaction `c599a1746e491095a2c673feadfb7b4a21b41d4e1a1675eb386a7c71d7e666e3`.
At this point I've assumed that the `-f` is to be used only with the multiple receivers and only if the sum of amounts is lower than the amount to claim.

So (since in agreement to the issue #150 it's not possible to claim tokens burned with the transaction `d8d9c1253fd7e68a9f7b66c48e0a7de45b6469e2a4f93af803d40d9db0c5845c`) I've tested the following commands using another one, which I know to be valid:
- `pobtoken claim  95b24015ffb46d82015b709d774542fc4a53ccf27f72d973ed3fb18c384a80ca 57d9d21e15cc3a624c532ccda2375fe7ae8985d6af6eb642b4d4f4d1534531e7 -r "[mwvsHNwNQ8eiRFGHNqnpD7EdoFk5zzAdYH, mnYTcGF8vVuSAYeoxxNaFWX94QUFM92YZf, mk9WFSTqgtTJbwb5g6pGpByTRbYKiSaX3w, n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL]" -a "[100, 30, 3, 0.1]" -f`
- `pobtoken claim  95b24015ffb46d82015b709d774542fc4a53ccf27f72d973ed3fb18c384a80ca 57d9d21e15cc3a624c532ccda2375fe7ae8985d6af6eb642b4d4f4d1534531e7 -r "[mwvsHNwNQ8eiRFGHNqnpD7EdoFk5zzAdYH, mnYTcGF8vVuSAYeoxxNaFWX94QUFM92YZf, mk9WFSTqgtTJbwb5g6pGpByTRbYKiSaX3w, n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL]" -a "[100, 30, 4, 0]" -f`
and 
- `pobtoken claim  95b24015ffb46d82015b709d774542fc4a53ccf27f72d973ed3fb18c384a80ca 57d9d21e15cc3a624c532ccda2375fe7ae8985d6af6eb642b4d4f4d1534531e7 -r "[mwvsHNwNQ8eiRFGHNqnpD7EdoFk5zzAdYH, mnYTcGF8vVuSAYeoxxNaFWX94QUFM92YZf, mk9WFSTqgtTJbwb5g6pGpByTRbYKiSaX3w, n3qWzoBX24abCSq8hMMzmCb8dh5ePnhdmL]" -a "[100, 30, 4, 10]" -f`,

but in all the three cases nothing was credited to the 4 addresses mentioned in the command.
So I was wondering what is the usage of the `-f` flag in this context? Would it make sense to suppress it or you'd prefer to keep it for your needs?

**Comment by d5000** [comment]
Oh, I apologize if you lost time with this flag. It's a flag I created to debug the AT/PoB token code (in the help this is also stated that it's a debugging option).

I have deleted the message recommending `--force` to override the amount limit (for the next update), and will probably eliminate the option before launch.

I think this can be closed.
