### ISSUE TITLE
testing pobtoken create_tx with ATToken decks

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#149]
FYI, feeling that the PoBtoken and ATToken are very similar I've tested `pobtoken create_tx` command with the ATToken decks.

- The `pobtoken create_tx ATTokenNotPoB 1.1234` command has raised `Error: No valid address string or non-existing label in the extended configuration file.` error, as well as `pobtoken create_tx ATTokenNewSpec 1.1234`.

- For the `pobtoken create_tx f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d82 1.1234` I've got `Error: End deadline for burn or gateway transactions of this token is is block 250000.` and for `pobtoken create_tx dbefb8c9fcb4ed2bb2722abb177188b9e7d8cde55e4163fff9c5e5ca374706e1 1.1234` I've got `Error: End deadline for burn or gateway transactions of this token is is block 150000.`.

- The `pobtoken create_tx 7a2ae406ddf44ddb17532d4888fdc14573f52749445e9e014075c9f83cbe556f 1.1234` command has produced a regular transaction `97fd0b0ecbfc49dc3eae05c1eec92637dec6be7f7cd2edc1d27d6f977b9d36ef`, but I was not able to claim tokens using the `pobtoken claim 7a2ae406ddf44ddb17532d4888fdc14573f52749445e9e014075c9f83cbe556f 97fd0b0ecbfc49dc3eae05c1eec92637dec6be7f7cd2edc1d27d6f977b9d36ef` command (I've produced `c59d979cd8ebc461d1fc3d9cf19d7814854983aa73bfc4f36fdf147185945e6c`, `6030070f350cc098fe9fbfe30268fc7db452db0d13c1c393fbebb29ed0137b88` and `bc83c403405eb49428f17a496deb8d1b5935927d2322507581ed3d871f8ed41a` but my `token balances -t 7a2ae406ddf44ddb17532d4888fdc14573f52749445e9e014075c9f83cbe556f` output has remained always `{'n3MtPoPaAREU5GEhAErBPuju83bVog2opz': 0}`.

- Trying `attoken claim 7a2ae406ddf44ddb17532d4888fdc14573f52749445e9e014075c9f83cbe556f 97fd0b0ecbfc49dc3eae05c1eec92637dec6be7f7cd2edc1d27d6f977b9d36ef` command hasn't changed the situation. I've produced transaction `b4db461dc2420ea9411709e0041e557feacc1a7975823372851a0011f8b6bae8`, but the `token balances -t 7a2ae406ddf44ddb17532d4888fdc14573f52749445e9e014075c9f83cbe556f` output was still `{'n3MtPoPaAREU5GEhAErBPuju83bVog2opz': 0}`.

**Comment by d5000** [comment]
- `ATTokenNewSpec` is not longer a valid token, it was an old testing token so it will not work correctly. I've seen that `pacli deck list -a` does show it, so at least its "magic bytes" identifying it at the start are there but the structure seems incorrect.
- Both f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d82 and dbefb8c9fcb4ed2bb2722abb177188b9e7d8cde55e4163fff9c5e5ca374706e1 show the correct deadlines.
-  With `attoken create_tx 7a2ae406ddf44ddb17532d4888fdc14573f52749445e9e014075c9f83cbe556f 1.1234` I was able to create the gateway tx, claim the tokens and get them credited.

As written in issue #150 , I have modified the structure to disallow `pobtoken create_tx`. This is redundant with `pobtoken burn_coins`. The structure of the command was identic though.

So as in issue #150 I think probably the bug has been fixed already.

Please close if no more problems appear here.

**Comment by buhtignew** [comment]
I've just been able to create a transaction `1a7fb3b69cde609467e5067e8573a189d6277aa9d71e0ddf8784d44fb480c931` for the PoB deck using ATToken command `attoken create_tx ATTokenNewSpec2 1`.

After I've created that transaction it was visible both in `transaction list ATTokenNewSpec2 -b -u | grep 1a7fb3b69cde609467e5067e8573a189d6277aa9d71e0ddf8784d44fb480c931` and `transaction list ATTokenNewSpec2 -g -u | grep 1a7fb3b69cde609467e5067e8573a189d6277aa9d71e0ddf8784d44fb480c931` outputs.

Then I've claimed it using `attoken claim ATTokenNewSpec2 1a7fb3b69cde609467e5067e8573a189d6277aa9d71e0ddf8784d44fb480c931` command (transaction `206a4a82f074c404c519b005100b41a527c30233722277c936006b173e686734`) and now I can see it in the `token transfers ATTokenNewSpec2 | grep 206a4a82f074c404c519b005100b41a527c30233722277c936006b173e686734` output.

At this point it seems like there is no need to have `pobtoken burn_coins` and `pobtoken claim` commands since the analogous `attoken` commands can do all the job (I haven't checked yet if we have the same situation with the `spawn` command as well).

I don't know whether we can consider merging both categories into one or into the `token` category or if it makes more sense on the opposite to split them more apart by adding checks that do not let using `attoken` commands in place of their `pobtoken` cousins.

**Comment by d5000** [comment]
>At this point it seems like there is no need to have pobtoken burn_coins and pobtoken claim commands since the analogous attoken commands can do all the job (I haven't checked yet if we have the same situation with the spawn command as well).

`burn_coins` is obviously not available for `attoken`. The `claim` command is indeed identic in both cases, but the `spawn` command is different.

For me it's an usability improvement if you can fastly create a PoB token with `pobtoken spawn` instead of something like `attoken spawn -b`, and to `burn_coins` is more intuitive than something like `create_tx -b`. Also in the case of a merge the difference between AT and PoB tokens is a bit lost.

So I'm tending to leave everything as it is.

**Comment by buhtignew** [comment]
Agreed.
