### ISSUE TITLE
Flag's collision in pobtoken deck_spawn command

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#152]
I've tried to run `pobtoken deck_spawn my_first_pod_deck -m 1.5 -n 3 -f 490000 -e 500000` command and got the following message:
```
ERROR: The argument '-n' is ambiguous as it could refer to any of the following arguments: ['name', 'number_of_decimals']
```
_
The same for the `attoken deck_spawn` command.

**Comment by d5000** [comment]
Did 3 changes:

- solved ambiguity, `-n` now works for `number_of_decimals` (positional arguments were renamed)
- renamed command to `attoken/pobtoken spawn`, as we don't really need the deck_ prefix and we have the "token" name already in the command
- supported labeled/named addresses for the tracked address (second positional argument).

Commit: 22b7878

Can be closed if everything works.
