### ISSUE TITLE
Editing the deck's global name

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#154]
As I've mentioned in #153 I've tested the `pobtoken deck_spawn my_first_pod_deck -m 1.5 -n 3 -f 490000 -e 500000` command giving a wrong name to my deck, by mistake.
This mistake has given me a reason to think that the other users may need to change his deck's global name after their creation.

I don't know whether such a feature would be feasible and whether it can be used by the scammers but if you think it may make sense we can discuss about here.

**Comment by d5000** [comment]
This will not be supported, PeerAssets doesn't allow changes to the basic parameters natively, and it would be extremely complex to add it as an extension.

You can simply create a new deck in this case, you only lose 0.01 of tx fees :)
