### ISSUE TITLE
pobtoken deck_spawn with the --number_of_decimals flag

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#155]
As mentioned in #153 yesterday I've created a deck `1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7` using the `pobtoken deck_spawn my_first_pod_deck -m 1.5 --number_of_decimals 3 -f 490000 -e 500000` command.

Today I've been trying to test whether the number of decimals I've set up works correctly.

So I've created a burn transaction (`bcc8bf6db27a6a2de191ed7f31dddd4dd170eab34688147767961786a88124eb`) using the  `pobtoken burn_coins 0.1113 -i 1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7` command.

I can see it pending in the `transaction list 1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7 -b -u` output:
```
{
    'txid': 'bcc8bf6db27a6a2de191ed7f31dddd4dd170eab34688147767961786a88124eb',
    'value': Decimal('0.1113'),
    'outputs': [0],
    'height': 491555
}
{
    'txid': '71a7283f5915bcc15481b8911137827d54cf09c956b30d7a22bec044e6673ca8',
    'value': Decimal('1.0'),
    'outputs': [0],
    'height': 491555
}
```
But I'm not able to claim it.
I've launched the `pobtoken claim 1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7 bcc8bf6db27a6a2de191ed7f31dddd4dd170eab34688147767961786a88124eb` command more than once and have produced the following claim transactions:
- `fbf3a4a60e2c9864627628472ad2e192a082239006de3dedbb0e25a41781ae63`
- `3b6e12198f5bae40d5cf14c2ee2ff9362a401783d1d4e59b5da3736d647cfcdd`
and
- `5851dcf12ef105b1b44ca6f14973004f96eb8755ac6a560c1222d5e4baae7ff5`

I've burned another portion of coins with `pobtoken burn_coins 0.1114 -i 1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7` (transaction `0f80484cbb1cfb173975724468f3f7775a949082a41219321f791d825efa6639`) and I'm not able to claim that amount as well.

Then I've burned an amount with less numbers after the comma using the `pobtoken burn_coins 0.111 -i 1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7` command (transaction `204a5a2a07538a8ef6fa92fb1592c78aefbd6832c3278af897af60bf5f79a046`) and was able to claim it (transaction `848569c0a447cb6e439a22ea90a21065cabae28f42cbc3968af3dea83a883910`).

Maybe to avoid people having their burn transactions pending we can make a check before the amount is burned that the number of decimals is smaller or equal to the deck's limit?
Or we can let the code cutting the amount automatically either while burning or while claiming.

**Comment by d5000** [comment]
This is a bug. People should be able to claim tokens for all coins they burnt, irrespective of the number of decimal places. Thanks for spotting it.

The bug was in pypeerassets, an int() was missing. It was fixed at pypeerassets commit 0bf3c26.

If everything works now as expected the issue can be closed, on my end it worked.
