### ISSUE TITLE
pobtoken burn_coins with insufficient funds

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#156]
I've noticed that while the `pobtoken claim` command has the long error message hidden behind the `Error: Insufficient funds.` output, the `pobtoken burn_coins` still outputs the version that is not that user friendly.
Maybe we can implement the same short message in this case as well.

**Comment by d5000** [comment]
This was already fixed in an earlier commit, just tried it and the short red error appears. Closing thus.
