### ISSUE TITLE
pobtoken deck_spawn with the -f flag

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#157]
As mentioned in #153 I've created a deck using the `pobtoken deck_spawn my_first_pod_deck -m 1.5 --number_of_decimals 3 -f 490000 -e 500000` command so I was wondering what is the function of the `-f` flag.

My expectation was that the `transaction list 1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7 -x -g` for instance would begin scanning from the first block of that deck, but when I've launched that command it's begun scanning from the block 0.

So my question is: does the `Specify a start block to track transactions from.` line in the `pobtoken deck_spawn` help means that the user should first check manually the first deck's block using `token show 1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7 -f -i` command, for instance, and then launching the `transaction list 1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7 -x -g -f 489999` command, in this case?
Or there is some other case in which that first block data is being checked or used automatically?

**Comment by d5000** [comment]
Okay, now let's tackle the spawn commands ...

First to your question: The `-f` flag allows you to define a start block for the token. Burn or gateway transactions before that block will not be taken into account for the token distribution. The `-e` flag in contrast allows to define an "end deadline" in the same way (transactions after this block cannot result in valid token claims).

> My expectation was that the transaction list 1991d3d80c5df0d7c7b90afd4acf67d398cf8868f3a48b7568a96871bcc6f8e7 -x -g for instance would begin scanning from the first block of that deck, but when I've launched that command it's begun scanning from the block 0.

Your expectation here is correct. I had simply not implemented that into the `transaction list -x` command.

Added that feature in commit bcfb941.

Can be closed if everything works (was pre-tested).

**Comment by buhtignew** [comment]
Works as expected, the only thing I've noticed is that the scanning process is not observable, so while the command is running it may seem like it's just stuck. Is there any additional flag to be used in order to make the scanning evident?

**Comment by d5000** [comment]
You're correct, transaction list did show actually block heights only when the `-l` option was on. That was probably a side effect of an earlier change. Fixed in 4872377, pre-tested and closed as the bug was obvious and you had already closed the issue.
