### ISSUE TITLE
token info TOKEN vs token show TOKEN -f -i

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#159]
I was wondering whether it would make sense to suppress the `-i` flag in `token show` command and to display its output in the `token info`, since `token info TOKEN` seems more easy to remember than `token show TOKEN -f -i`.

**Comment by d5000** [comment]
`token info` is a vanilla command (deck info) and shows much less parameters than `token show -i`. It would take considerable work to integrate both commands, but would not be impossible.

But the main reason I'm objecting it is that getting more information is for me an important addition to the deck/token show command and matches well into the whole "concept" we created in long discussions around the "show/list/set" command system.

We don't have an `info` command in no other command classes, but in the case we centralize the "more information" function into "info" for decks, we would have also to add an "info" option for other classes.

For this reason I'm against implementing this, so you can close the issue.
