### ISSUE TITLE
attoken deck_spawn with some wrong parameter

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#166]
I've been testing `attoken deck_spawn` command and have tried to see whether it accepts by chance the partial names of the flags. 
So I've replaced the `--number_of_decimals` with the `--number` and run `attoken deck_spawn super_at msAzW8dLyCNhnashwThAo2rUNKBycqt7yv -m 13 --number 10 -f 506000 -e 505942 -c mjXqewNUxUCW4v6bQ7CzhRAVMLHmQ6ktxN`.
It has produced a regular transaction `9f19146f0ac466cb584ecae3c2d72efd236ad1a13cb119fd77ff1b99ef6bc95a` but afterwards the following output was provided:
```
ERROR: Cannot find key: --number
Usage: pacli attoken deck_spawn super_at msAzW8dLyCNhnashwThAo2rUNKBycqt7yv -m 13 --number 10 -f 506000 -e 505942 - <value>
  available values:      hex

For detailed information on this command, run:
  pacli attoken deck_spawn super_at msAzW8dLyCNhnashwThAo2rUNKBycqt7yv -m 13 --number 10 -f 506000 -e 505942 - --help
```
So it seems like the wrong flag was ignored, and after the command was executed the check whether there are wrong flags included was performed.
Since the check is already in place, maybe it would make sense to put it before the command being run.
_
As you can see from the above command and from another one I've run afterwards (`attoken deck_spawn super_at1 msAzW8dLyCNhnashwThAo2rUNKBycqt7yv -m 13 --number_of_decimals 10 -f 506000 -e 505942 -c mjXqewNUxUCW4v6bQ7CzhRAVMLHmQ6ktxN`) it seems like I was able to produce the deck that is never valid because the end block happens before the first one.
In any case maybe it doesn't make too much sense preventing users from doing this by placing an additional check into the code.

**Comment by d5000** [comment]
>  Since the check is already in place, maybe it would make sense to put it before the command being run.

This is managed by the Fire library, so it's nothing I can change.

> In any case maybe it doesn't make too much sense preventing users from doing this by placing an additional check into the code.

As the check is very easy to implement, I've just done it and tried it successfully. Commit: 85d938a

Can be closed.
