### ISSUE TITLE
attoken spawn with the fractional number of decimals 8-\

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#171]
While I was inquiring why is it that I thought to have received a [different message in case of `attoken spawn` and `pobtoken spawn` commands if used with the fractional multiplier](https://github.com/slimcoin-project/pacli/issues/153#issuecomment-2262362488) I've discovered to have used the fractional number of decimals instead, so I've basically run `attoken spawn` with the `-n` instead of the `-m` flag (the exact command was `attoken spawn test_att1 myHPHhnncUaiFQGqN1FK2qFtwcfPE4Bkqc -n 1.3`).
The message I've got was:
```
      General error raised by PeerAssets. Check if your input is correct.

        If you gave a deck as an argument, a possible reason for this error is that you need to initialize the deck.

        To initialize the default decks, use:

        pacli deck init

        To initialize a single deck, use:

        pacli deck init DECKID
```
The fractional number of decimals doesn't make any sense of course, so I'm not sure we should consider doing anything about at this case.

**Comment by d5000** [comment]
I think we can leave this as it is. "your input may not be correct" is what the user then sees, and that's correct in this case.

I'm trying to fine-tune the error message a bit, so the part about decks is shown mainly when really the uninitialized deck is the problem.

I think this can be closed thus.
