### ISSUE TITLE
Default --sign and --send values in dex

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#172]
I've begun looking into the `dex` group of commands and have seen that in case of the `dex lock` command both `--sign` and `--send` are defaulted to `false` as well as the `--sign` of the `dex exchange` command, while the default value of the `finalize_exchange` `--send` flag is set to `true`.
I'd like to ask whether it's intended because we've set those values to `true` in the other groups, but I assume that while exchanging tokens with strangers one should be a little bit more careful. If this is the idea, I was wondering why the `finalize_exchange` command  has the `true` default value.

**Comment by d5000** [comment]
This was simply still not updated to the "sign/send=True" policy and had no "deeper" reason. I have set all values to `True` already in an earlier update. Thus I'm closing.
