### ISSUE TITLE
Would it make sense changing the dex group of commands into swap?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#173]
I'd like to ask you whether it would make sense to rename the `dex` group of commands into `swap` in order to prevent people having too much expectations for the moment (we are not providing a decentralized offer's list for instance and so on).

**Comment by d5000** [comment]
Technically there are no objections.

In this case, it could make sense to rename the `exchange` command to `create` (as a speaking command "create swap") and the `finalize_exchange` to `finalize`.

The commands related to locking would however be a bit less "speaking". But in general I think it's an idea worthy to consider. Let me think a bit about it.

**Comment by d5000** [comment]
I have decided to implement that change. The commands are now:

- swap lock (ex: dex lock)
- swap create (ex: dex exchange)
- swap finalize (ex: dex finalize_exchange)
- swap list_locks (ex: dex list_locks)
- swap select_coins (ex: dex select_coins)

Commit is b7b61f9.

I recommend closing this issue and open one for each command to test.

**Comment by buhtignew** [comment]
Great!
