### ISSUE TITLE
proposal period with the -s and -e flags

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#178]
I've noticed that while the `proposal period PROPOSAL PERIOD -s` works correctly (for instance `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432 D1 -s`), the `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432 -s` output is a bit strange: `141232`.
 Whereas the `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432 -e` is void, which is also strange since the flag should be probably just ignored returning the same output of the `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432` command:
```
'Next block: 512610'
'Period E. Distribution finished (reward claiming allowed if proposal '
'was successful). (start: 141232, end: End of chain)'
```

**Comment by d5000** [comment]
Also here (like in issue #177), I don't understand the problem. For the period E, which is the period where this proposal is currently "in", there's no value for end because it lasts always until the end of the chain. This is also mentioned in the help.

I think there's a general misunderstanding?

**Comment by buhtignew** [comment]
Like in the issue #177 I'm not able to launch `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432 D1 -s` at the moment.

However in this case I'm able to explain what I meant:
1) If I launch `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432 -s` it's a wrong usage of the command because the PERIOD is missing, nevertheless the output I'm getting corresponds to beginning of the period E (`141232`).
My expectation was to see the `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432` output instead if the `-s` is ignored or at least `0` which would match the beginning of the period A0 of the proposal, i.e. in my understanding the beginning of the beginning :-)
2) If I launch `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432 -e` (which is also a wrong way to use the command as above) I'm not getting any output at all which is also a bit surprising because seeing the previous section I was expecting the Next block info from the `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432` output or, if the `-e` is ignored, the output of the `proposal period 472f2420820c99333969bba0ecb7fc4080b7e2f6d8bb65756070a31b450b7432`.

**Comment by d5000** [comment]
You can use the command without any period, and then it will show the values of the current period you're in.

As in this case it's period E, which has no end value, the result of the command with `-e` / `--end` is nothing (I checked and this is also mentioned in the help).

So your usage isn't wrong, it's working as expected.

I just saw it's however a bit counter-intuitive that the command is more verbose normally if you use it without the period string (D1, E etc.), while when you use it with -s and -e flag, it only shows the raw values of start or end. I don't know if that can be improved in any way. Perhaps the "verbose" output could get an extra flag? I have to think a bit about it, but priority is not the highest :)

The help was also a bit misleading for the `-e` and `-s` flags. I have changed it, will be uploaded with the next update.

**Comment by buhtignew** [comment]
Everything is clear to me now.
We can close this issue.
