### ISSUE TITLE
transaction list policy change for -g -b and -c options

### ISSUE THREAD

**Issue by d5000** [slimcoin-project/pacli#183]
I have made some changes to the flag policy of transaction list.

When working on issue #162 I realized that the `-w` option did sometimes output transactions which were not sent from a wallet address, but had some other output spent to a wallet address or even a P2TH address, which is not desired in the case of `-b`, `-g` and `-c` because in this case the user normally wants to know transactions sent from his own wallet so they can claim them, or see their own claim transactions.

So I made the `-w` mode of these three options stricter: The first sender of the transaction has to be in the wallet and not be a P2TH address. As the second (and third etc.) senders are not taken into account when distributing AT or PoB tokens, transactions where the first sender is not in the wallet but the second/third is, are ignored.

I added a new mode to `-b` and `-g` (`-c` already had it but was undocumented) which is similar to the old `-w` mode but includes P2TH addresses as possible origin or receiving transactions: If you use the command now without `-w` nor `-o`, this means that you will get _all_ burn and gateway transactions, including those which are from other users if one of the sending or receiving addresses is in your wallet, P2TH or not.

This means that a slight tradeoff had to be accepted: to see the transactions made from your current main address, you have to enter `-o` (without any address). `-o ADDRESS` is also mandatory if trying to check another address for burn/gateway/claim transactions.

Help was clarified in this sense.

The `-x` variants have not been changed as they are not affected by this "problem" as long as they don't accept the `-w` mode.

At commit 4c6cb49 all those changes were implemented.

**Edit: Clarification**: In the case of gateway transactions where yourself did not launch the token, you will normally not have access to the gateway address in your wallet, so in the mode without `-w` only your own wallet gateway transactions will be shown. But it will include those transactions where for example an output was spent to your wallet. I'm about to clarify this also in the help for the next update. In the case of burn transactions you will see all including those that never touch your wallet addresses, because the burn transactions are all saved in the wallet (afaik).

**Comment by d5000** [comment]
Just want to add that this issue can be closed at any time if everything is ok related to it :)

**Comment by buhtignew** [comment]
Sorry for it has taken me so much time to put my hands on this, but finally I'm here.

> As the second (and third etc.) senders are not taken into account when distributing AT or PoB tokens, transactions where the first sender is not in the wallet but the second/third is, are ignored.

But what other senders along of those of my wallet's could be included as senders in my transaction except the P2TH ones?

**Comment by d5000** [comment]
> But what other senders along with those of my wallet's could be included into my transaction except the P2TH ones?

The case is indeed relatively rare, but there are several possibilities, like DEX transactions, CoinJoins and other transactions where you build the transaction with inputs from several senders

These cases will almost never happen in the case of burn/gateway/claim transactions (although I can imagine use cases for CoinJoins), but it's anyway important to clarify the policy, so the user knows that the transactions listed in `-b` and `-g` can always be claimed from this wallet.

P2TH inputs are indeed the main use case covered by this policy change.

**Comment by buhtignew** [comment]
Thank you very much for the explanation.
I hope to have understood this change of policy and if so I think it makes great sense.
I'm closing this issue again.
