### ISSUE TITLE
attoken claim incoherent message for the future decks

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#189]
There is the attoken deck `c73bd45abd75aa240f8485518b02bfb8160b1a41a920bb64b7a11e28071cec47` that will become valid on the block 70000 and its at_address is `mgpiP2Dc5QweKFS55HvRqsWyQ6PMXJCVCk`.

There is a transaction with the following `transaction show bc1da760cb976ea659dfb9f547d01782ab69cdef31f30eca1fb00c0fb7499ffc -s` output:
```
{
    'inputs': [
        {'sender': ['n3MtPoPaAREU5GEhAErBPuju83bVog2opz'], 'value': 104.51}
    ],
    'outputs': [
        {'receivers': ['mmSLiMCoinTestnetBurnAddress1XU5fu'], 'value': 3.0},
        {'receivers': ['mgpiP2Dc5QweKFS55HvRqsWyQ6PMXJCVCk'], 'value': 101.5}
    ],
    'blockheight': 484357
}
```
So it's an existent transaction with a number of confirmations, that contains the address `mgpiP2Dc5QweKFS55HvRqsWyQ6PMXJCVCk` as receiver.

I've tried to claim tokens using the above deck and transaction by running `attoken claim c73bd45abd75aa240f8485518b02bfb8160b1a41a920bb64b7a11e28071cec47 bc1da760cb976ea659dfb9f547d01782ab69cdef31f30eca1fb00c0fb7499ffc` and got the following error message:
```
Error: This transaction does not spend coins to the tracked address
```
Which is untrue.
_
I've also run `attoken claim 93f5e596cf80d24f8809dff4f22b2d4e082550c446aa5b1a04dd157aee1c87bd bc1da760cb976ea659dfb9f547d01782ab69cdef31f30eca1fb00c0fb7499ffc` (on the deck `93f5e596cf80d24f8809dff4f22b2d4e082550c446aa5b1a04dd157aee1c87bd` that has the same at_address but doesn't have any starting date) and everything went as expected.
I've run the `attoken claim 90c4ae62e36a714a37a26dce28e23542798ebf31da44ca58b00d10fee156c91f bc1da760cb976ea659dfb9f547d01782ab69cdef31f30eca1fb00c0fb7499ffc` command as well (using the
deck that has the same at_address but its starting date occurs after the block in which the mentioned transaction was confirmed but before the current blockheight) and everything went in the same way as described [here](https://github.com/slimcoin-project/pacli/issues/162#early_token_claiming) for the `pobtoken claim` command, i.e. the command was executed smoothly, the transaction was created, but the tokens weren't credited (I've already included this info into the *Nice to have* issue [here](https://github.com/slimcoin-project/pacli/issues/167#nice_early_claim)).

**Comment by d5000** [comment]
> There is the attoken deck c73bd45abd75aa240f8485518b02bfb8160b1a41a920bb64b7a11e28071cec47 that will become valid on the block 70000 and its at_address is mgpiP2Dc5QweKFS55HvRqsWyQ6PMXJCVCk.

Are you sure about the address? I get `msAzW8dLyCNhnashwThAo2rUNKBycqt7yv` as the at_address when I retrieve info of this deck with `deck show TOKEN -i`.

**Comment by buhtignew** [comment]
You are right. My OP was basing on the wrong data.
Closing.
