### ISSUE TITLE
`pacli config show VALUE CATEGORY -e/extended -l/--label` command

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#19]
I have a transaction stored in extended file with the label `new`.
When I run `show f4e26f3a14a7fbe7ea45bd60ad9005ebbaa36a3cecd864c7f3ef517c5fe27c86 transaction -e -f` it works fine and I'm getting the following output:
```
Label(s) stored for value f4e26f3a14a7fbe7ea45bd60ad9005ebbaa36a3cecd864c7f3ef517c5fe27c86:
[
    {
        'new': 'f4e26f3a14a7fbe7ea45bd60ad9005ebbaa36a3cecd864c7f3ef517c5fe27c86'
    }
]
```
However when I run `config show f4e26f3a14a7fbe7ea45bd60ad9005ebbaa36a3cecd864c7f3ef517c5fe27c86 transaction -e -l` I'm getting the following output:
```
ERROR: The argument '-l' is ambiguous as it could refer to any of the following arguments: ['label_or_value', 'label']
```
The same command with the full word as a flag, i.e. `config show f4e26f3a14a7fbe7ea45bd60ad9005ebbaa36a3cecd864c7f3ef517c5fe27c86 transaction -e --label` works as expected.

**Comment by d5000** [comment]
I have changed this option so the conflict disappears. `-l` should now work as a short form of `--label`.

Commit: becbaea3fd041b352a5845c73da91a97d0af04f0

**Comment by buhtignew** [comment]
You've inverted the position of the `-e` flag as well, haven't you?

**Comment by buhtignew** [comment]
This works, I'm closing the issue.
