### ISSUE TITLE
address cache testing

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#193]
I've run `address cache mie75nFHrNAHHKfQ141fWfWozdMnaec8mb -e` on the address I haven't done any caching previously and got the following error message:
```
Traceback (most recent call last):
  File "~/.local/lib/python3.12/site-packages/pacli/blocklocator.py", line 70, in delete_address
    del self.addresses[address]
        ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'mie75nFHrNAHHKfQ141fWfWozdMnaec8mb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 479, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 778, in cache
    return ei.run_command(self.__cache, addr_str, startblock=startblock, blocks=blocks, chain=chain, keyring=keyring, erase=erase, force=force, quiet=quiet, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_interface.py", line 34, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 792, in __cache
    return bu.erase_locator_entries(addresses) # TODO: improve this allowing startblock and endblock.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/blockexp_utils.py", line 311, in erase_locator_entries
    locator.delete_address(address)
  File "~/.local/lib/python3.12/site-packages/pacli/blocklocator.py", line 72, in delete_address
    raise ei.PacliInputDataError("Address not found.")
          ^^
NameError: name 'ei' is not defined
```
_
I've also discovered that it's actually possible to run `address cache` with the `-s`  flag but without the `-f` flag (for instance like this `address cache mie75nFHrNAHHKfQ141fWfWozdMnaec8mb -s 563000`) the only inconvenience is to enter "yes" to confirm the choice.
So the `-f` flag doesn't really "forces" the discontinuous scanning, it avoids having the yes/no dialog.
By other hand the `address cache mie75nFHrNAHHKfQ141fWfWozdMnaec8mb -e -f` doesn't work in  that way and there a "yes" to reply to, since the `-f` flag is basically ignored.
I remember we've already introduced a flag that prevents appearing the yes/no dialog for some other command, but I can't find which one, maybe we could use that flag for this command as well and enable if for the `-e` flag?
Or we can prevent the possibility of using the `-s` flag without the `-f` flag.

UPDATE 03-10-2024:
Seems like with the `-k` flag the `-f` flag is required and there is no yes/no dialog in case of the `address cache keyring_new -k -b 100 -s 565000` command for instance.
The message I'm receiving is in line with the expectation I had for the command run both for the keyring addresses as well as non-keyring addresses:
```
There was a previous caching process. Continuing it from last cached block 200 on.
To cache other block heights, use -f / --force or erase the affected addresses from the block locator file with 'address cache -e'.
Processing block: 300
```

**Comment by d5000** [comment]
First bug with inexistent addresses was fixed.

>  So the -f flag doesn't really "force" the discontinuous scanning, it avoids having the yes/no dialog.

Yes, this is correct. In theory we can also abort discontinuos scanning if the user doesn't enter `-f`, then it would be more consistent with other uses of the --force flag.

I remember you had problems with your shell with this "confirmation dialog", would you prefer me to replace more instances of this dialog with a force flag and otherwise the user is prompted an error? This would be no problem, I'm not so fond of this dialog myself.

**Comment by buhtignew** [comment]
> In theory we can also abort discontinuos scanning if the user doesn't enter -f...

I think it would make sense. 
For the moment we have the following message:
```
There was a previous caching process. Continuing it from last cached block 563100 on.
```
But I'm not sure any user that is trying to make a discontinuous caching would like the scanning to go on if he has entered a wrong command.
So aborting would be more appropriate in this case, IMO.

> I remember you had problems with your shell with this "confirmation dialog", would you prefer me to replace more instances of this dialog with a force flag and otherwise the user is prompted an error? This would be no problem, I'm not so fond of this dialog myself.

I think it would make sense and it would help my issue with the pacli_env, since for the moment I don't know how to solve it.

> This isn't related to the -k flag but to the presence of the address in the blocklocator.json file. This address was already cached. Try it with a "normal" (non-keyring) address label where the address was already stored in blocklocator.json, the output will be the same.

Tested as you suggested. You are right.

**Comment by d5000** [comment]
I'm leaving this open to remind me about the plan to remove the confirmation dialogs and replace them with `-f` flags, the other issues seem to be solved.

**Comment by d5000** [comment]
All dialogs with one exception (the option to enter another name if you initialized a deck and the label is already taken) were now replaced by command line options. In the remaining case I think it makes sense to keep the input dialog, because the user can so rapidly decide the label he wants to assign.

So this issue can be closed.

**Comment by d5000** [comment]
Look at the `deck list` for several decks with the same global name. For example, all those decks named `conflicting` I created just for the purpose to test this case.

Then initialize the latest (with less confirmations) of them you haven't initialized yet, or any deck where an earlier deck has also the same global name. An example which worked in my case was 00f37640c4c5844f587686fb188324db5bf9428ecc0d1d31a0c6ed9258acf186.

It will print out a message that an earlier deck exists with the same global name (the idea is that the earliest deck with this name has always priority), and ask you to enter a label.

**Comment by buhtignew** [comment]
I've tested this functionality.

It creates an issue for `pacli_env` (the same as with the other dialogs we had) I'm not able to solve at the moment.

Would it be possible to drop this dialog as well by asking the user to set up the local label manually? 
Like it already happens if I try to initialize another `conflicting` deck after this one, when I'm receive the following message:
```
Store manually using 'pacli deck set LABEL 75b324876cbfbc49af37ff9bcbba1fc5493e10ce89b0cae6f05168539b3cdea8' with a custom LABEL value.
```

**Comment by d5000** [comment]
Alright, I've removed the dialog.

Commit: c1f2c94

Can be closed.
