### ISSUE TITLE
Is it possible that yes/no dialog doesn't close the child process completelly?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#195]
I'm working on the `pacli_env` tool and have found the solution the main compatibility issues I had, but there is a strange thing (which by the way I'm not able to reproduce if I'm using the `pacli` command directly): in case I'm launching commands that have a yes/no dialog for instance if I run `address cache mie75nFHrNAHHKfQ141fWfWozdMnaec8mb -s 563700` command it seems like the child process is not being shut down completely or as if the code weren't passing from the child processes to the main one or the exit code wasn't released.

In fact I need to press an extra "Enter" to make my `pacli_env` begin working normally, which is not a big deal for me, but since I'd like to publish the code for the others I'd prefer it to be without this small things to explain.

Maybe you have an idea about what can be the issue, basing on my above explanation?

Or perhaps it's the issue of the library I'm using, if so I'll need to change it to see whether the issue disappears.

**Comment by d5000** [comment]
I have unfortunately not really an idea here, my only guess is that it has to do with the input() function. If it helps, I'll paste the code of the function:

```
def confirm_continuation(text: str=None) -> bool:
    """UX element to confirm continuation entering 'yes'."""

    text = "Enter 'yes' to confirm to continue" if text is None else text
    print(text)
    cont = input()
    if cont == "yes":
        return True
    else:
        return False
```

**Comment by buhtignew** [comment]
I'm not enough into php coding, but would it be possible for you to terminate the child process created by input() function once the main command has run?
I've found [this page](https://learn-codes.org/php/51368-termination-of-php-child-processes) that seems to me to be pertinent to the topic.

**Comment by buhtignew** [comment]
At the moment I think this issue doesn't have to do with the child processes not terminated.
I'm closing this, in case I'll have anything to discuss about I'll reopen it again.
