### ISSUE TITLE
comparision of transaction list -b with transaction list -b -w

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#199]
I've discovered that the `transaction list -b` output has two transaction more than the `transaction list -b -w`: `3aea75c2011e15a75454a01c963eb6d26ebb8b62f39abc9e8428458a9b5290e8` and `779c17983503f4d236fd192fdd12e4571d2f94922da59b8a4df8ddd5db3d055f`.

By reading the line `Showing only transaction sent from this wallet (excluding P2TH addresses).` in the `transaction list -b -w` output I've originally thought that those two transactions had both to do with the P2TH addresses, but later on I've better checked the addresses that are involved in those transactions and they doesn't have to do with any P2TH address of any deck I can see in my `token list` output.
In fact the only two addresses involved in those transactions are `mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya` and `mmSLiMCoinTestnetBurnAddress1XU5fu` the later is the testnet burn address, while the former seems to be just my address and I can see it labeled as `new_one` in my `address list` output.

Since originally I was erroneously thinking my own address was the standard PoB token P2TH address instead I've set it as main and have burned coins from there to understand things better
(transaction `5a495f4c93bd253a0af1920ab2899583f629045832392b1d0ea85c56db37d13c`).
_
I've compared the `transaction list "dICO test"  -b` with the `transaction list "dICO test"  -b -w` output and the difference was one of the above transactions, `3aea75c2011e15a75454a01c963eb6d26ebb8b62f39abc9e8428458a9b5290e8`.

I've also compared `transaction list ATTokenNotPoB  -b` with `transaction list ATTokenNotPoB  -b -w` and the difference was `3aea75c2011e15a75454a01c963eb6d26ebb8b62f39abc9e8428458a9b5290e8` and `779c17983503f4d236fd192fdd12e4571d2f94922da59b8a4df8ddd5db3d055f` transaction but not the new one, the `5a495f4c93bd253a0af1920ab2899583f629045832392b1d0ea85c56db37d13c`.

However since `ATTokenNotPoB` and `dICO test` are not PoB tokens (they are in fact ATtokens) I'm not sure to fully understand the meaning of the output provided for them by the `transaction list` command when used with the `-b` flag.

It's also not clear why some of the above mentioned burn transactions are included into those deck's `transaction list DECK -b` output and some are not.
_
Comparing `transaction list PoBSimplest  -b -w ` with the `transaction list PoBSimplest  -b` all the 3 transactions are included into the `transaction list PoBSimplest  -b` output. 

Seems like `transaction list PoBSimplest  -b -w` is excluding those transactions as if they were P2TH transactions in the same way as the `transaction list -b -w` does.
_
Update 18-10-2024:
While testing `transaction list` with the `-c` flag I've discovered that the transactions `3aea75c2011e15a75454a01c963eb6d26ebb8b62f39abc9e8428458a9b5290e8` and `779c17983503f4d236fd192fdd12e4571d2f94922da59b8a4df8ddd5db3d055f` have been claimed for the `ATTokenNewSpec2` deck (so they are making part of the ` transaction list ATTokenNewSpec2 -c` output), but they haven't been claimed for `PoBSimplest` mentioned above (they are not reported in `transaction list PoBSimplest -c` output).
The new transaction `5a495f4c93bd253a0af1920ab2899583f629045832392b1d0ea85c56db37d13c` hasn't been claimed for `ATTokenNewSpec2` nor for `PoBSimplest`.

**Comment by d5000** [comment]
Which ist the deck you used for the first test?

And why are you checking AT (not PoB) decks with the `-b` flag? This won't give you any meaningful output.

**Comment by buhtignew** [comment]
> Which ist the deck you used for the first test?

I run both commands without a deck

> ...why are you checking AT (not PoB) decks with the -b flag? This won't give you any meaningful output.
 
When I've begun testing I've run `transaction list DTNewSpecv2 -b` by chance and got `Deck a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a is not an AT or PoB token deck.` so I've assumed the ATTokens would have some meaning in this context as well.
Maybe we should change this message into `Deck a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a is not a PoB token deck.` and include it as output for the ATtoken (or for whatever tokens that is not PoB) as well.

**Comment by d5000** [comment]
I've looked into the first issue, ran the commands on the wallet you provided me some months ago, and the problem is that the Slimcoin client -- more precisely, the `listreceivedbyaddress` RPC command which is the base for all address lists in pacli -- doesn't recongnize the address mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya as part of your wallet.

The reason it is shown in `address list` is that it has a local label, and locally labeled addresses are added even if they are not recognized by the mentioned command.

I will continue to investigate the issue. In theory this is a slimcoin bug and not a PeerAssets bug but maybe there's a way to fix it.

**Comment by buhtignew** [comment]
This works.

I've even created a burn transaction from a P2TH address (`005abd5d70ffdc3ed8b323ea2c61ae1d5f24523f6e31e865657bd28f2f8a8aeb`) and now my `transaction list  -b -t` is 71 and `transaction list  -b -w -t` is 70.
However I was not able to see that transaction with `transaction list ATTokenNotPoB  -o -b -u` (my main address is `muhhYam1NXMSUqKx4uSrfjS7N7Fcz6j6Qx` right now) nor with the ` transaction list ATTokenNotPoB  -o muhhYam1NXMSUqKx4uSrfjS7N7Fcz6j6Qx -b -u` since I'm getting the following error:
```
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 479, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 1703, in list
    return ei.run_command(self.__list, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_interface.py", line 35, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 1767, in __list
    txes = au.my_txes(sender=origin, deck=address_or_deck, unclaimed=unclaimed, wallet=wallet, keyring=keyring, advanced=advanced, quiet=quiet, debug=debug, burns=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/at_utils.py", line 298, in my_txes
    txes = show_wallet_dtxes(tracked_address=address, deckid=deckid, unclaimed=unclaimed, sender=sender, no_labels=no_labels, keyring=keyring, advanced=advanced, wallet=wallet, quiet=quiet, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/at_utils.py", line 57, in show_wallet_dtxes
    claimed_txes = get_claimed_txes(deck, sender, only_wallet=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/at_utils.py", line 276, in get_claimed_txes
    return set([c.donation_txid for c in eu.get_valid_cardissues(deck, input_address, only_wallet=only_wallet)])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_utils.py", line 452, in get_valid_cardissues
    ds = pa.protocol.DeckState(cards)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pypeerassets/protocol.py", line 562, in __init__
    self.calc_state()
  File "~/.local/lib/python3.12/site-packages/pypeerassets/protocol.py", line 625, in calc_state
    for card in self._sort_cards(self.cards):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pypeerassets/protocol.py", line 620, in _sort_cards
    return sorted([card.__dict__ for card in cards],
                                             ^^^^^
  File "~/.local/lib/python3.12/site-packages/pypeerassets/__main__.py", line 231, in find_all_valid_cards
    for card in validate_card_issue_modes(deck.issue_mode, list(unfiltered), provider, deck):
                                                           ^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pypeerassets/__main__.py", line 228, in <genexpr>
    unfiltered = (card for batch in get_card_bundles(provider, deck) for card in batch)
                                                                                 ^^^^^
  File "~/.local/lib/python3.12/site-packages/pypeerassets/pautils.py", line 307, in card_bundle_parser
    read_tx_opreturn(bundle.vouts[1]),
                     ~~~~~~~~~~~~^^^
IndexError: list index out of range
```
 _
Since haven't replied to this:
> Maybe we should change this message into Deck a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a is not a PoB token deck. and output it for the ATtoken (or for whatever tokens that is not PoB) as well.

I consider it's not an important matter, so I'll put it into the "Nice to have" thread.
_
I'd like to suggest the following improvement of the `transaction list -h`:
We can edit this: 
```
pacli transaction list DECK [-o [ORIGIN_ADDRESS]] -b [-u]
pacli transaction list -b [-o [ORIGIN_ADDRESS]]
pacli transaction list DECK [-o [ORIGIN_ADDRESS]] -g [-u]
```
into this:
```
pacli transaction list -b [-o [ORIGIN_ADDRESS]]
pacli transaction list DECK [-o [ORIGIN_ADDRESS]] -b -u
pacli transaction list DECK [-o [ORIGIN_ADDRESS]] -g [-u]
```
That would improve the readibility of the help, IMO. Specifically the `-u` flag is not really optional in case of the `-b` flag usage with the DECK, because the `-b` flag alone (i.e. without the `-u` flag) should provide the same result for all DECKs.
