### ISSUE TITLE
Doubled output in transaction list with the -p flag in some case

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#205]
While I was working on issue #204 I've discovered that in case I run `transaction list johns_first_ATtoken -g -u -p txid` each line of the output contains the same data (specifically the txid data) twice.
For instance like this:
```
'be0d450a893619268f91d024e8e1932fb7296f8614a798462cb7de1e1dee8dbc': 'be0d450a893619268f91d024e8e1932fb7296f8614a798462cb7de1e1dee8dbc',
'2182c64eb2d87eb787ba7d834c3fcc88e2b6e0422b8c8658e424d10d4379f065': '2182c64eb2d87eb787ba7d834c3fcc88e2b6e0422b8c8658e424d10d4379f065',
'42b5ee59ecd07e95da67a4d7254c1f162fc1e281ccc4650e47469cca226a1c77': '42b5ee59ecd07e95da67a4d7254c1f162fc1e281ccc4650e47469cca226a1c77',
```
I don't know how relevant is it, but maybe it can be improved somehow.

**Comment by d5000** [comment]
Take into account that this is not a query that really makes sense. The idea of the `-p` flag is to allow you to show parameters of the tx dictionaries, and the txid ... well, is already known. So why would you use the command in that way?

Sorry, I'm closing this.

**Comment by buhtignew** [comment]
In my case I just needed the list of unclaimed transactions ids.
In case someone needs it for scripting the list with doubled values is not comfortable, but I guess it can be easily re-elaborated into single values list.
So I'm reopening this for you to receive the reply and then closing this again.
