### ISSUE TITLE
address list with the -i and the -p flags

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#206]
While working on #204 I've launched `address list -i` and then `address list -p` to get a complete list of the addresses my pacli knows about.

I was expecting that the first output wouldn't contain any address from the second one and vice versa, since the `-p` flag description states `Show only P2TH addresses.` while the `-i` flag should `Show all genuine wallet addresses, also those with empty balances which were not named. P2TH are not included.`

However I've discovered that there is more than one address included in both lists in my case.

For instance: 
- mqZ5nqs6bpaAqEoEV9jVFfwsM3hBZD4C3J,
- mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn,
- mgMnRiMxfxsFgaaAahJFenvDxSJ1DtVour,
- mgiYjQjREbtKcKKH1kFXo1ycWCfGB5aZd7 and so on. 

For your convenience I've uploaded here the files containing the mentioned outputs:
[address_list_-i.txt](https://github.com/user-attachments/files/17488010/address_list_-i.txt)
[address_list_-p.txt](https://github.com/user-attachments/files/17488011/address_list_-p.txt).

At this point I don't really know whether the two flags description is not exact or the flags are not working as expected.

**Comment by d5000** [comment]
Found the problem, probably a side effect of my recent rewrite of the basic function for `address list`.

Fixed in commit 040e76b. Can be closed.
