### ISSUE TITLE
`config show LABEL CATEGORY [options] -e/--extended` usage

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#21]
I was wondering what are the `[options]` mentioned in the help file of the `config show` command in case mentioned in the title.

**Comment by d5000** [comment]
Basifally `-f/--find` and `-l/--label` (and `-q/--quiet`), isn't this clear from the docstring?

**Comment by buhtignew** [comment]
Now that the order of commands has been changed it's more clear and still there is the `-l` option mentioned in the ***Flags*** that may be considered a valid candidate by the advanced user (sorry if I'm mentioning this matter here as well, it's just to let you feel how it's perceived by the user).

**Comment by d5000** [comment]
I'm not getting what you mean, sorry :)
