### ISSUE TITLE
No --erase flag for token cache command

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#210]
I was working on [this reply](https://github.com/slimcoin-project/pacli/issues/196#issuecomment-2441035249) and have noticed that there is no `--erase` flag in `token cache` command as we have for the `address command`.

But maybe it's not relevant and could be only useful at the testing phase we are in.

Or maybe the deletion should be done using the `address cache` command.
_
UPDATE:
I'm strongly tempted to close this issue, since probably the advanced user that needs to erase the token caching would use `address cache "[ADDRESS1, ADDRESS2, ..., ADDRESSn]" -e` command.
I'm letting it here just in case you think for any reason that this "issue" can be important, if not, please just close it.

**Comment by d5000** [comment]
Just a short comment, you can indeed close that for now:

I indeed considered adding this option. However there's a problem with PoB and potentially also AT tokens. In the case of PoB tokens  cache also the burn address. If you erase this address too, then you'll modify the state of all burn tokens. Potentially this can also be a problem for gateway addresses used for different tokens.

So you would need a mode to erase only the entries in blocklocator.json for P2TH addresses but not for the burn/gateway address.

I think at least for now it is probably not worth the hassle to add this command (and probably a lot of messages and warnings ...) thus and as you already wrote, the users should simply erase the P2TH addresses manually.

**Comment by buhtignew** [comment]
Thank you for your additional explanation.
I'm closing this.
