### ISSUE TITLE
Error message in case of transaction list ATtoken -g command

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#212]
I've run `transaction list johns_first_ATtoken -g` and got the following error message:
```
Error: Gateway address mismatch. Probably you are using a command for PoB tokens for an AT token. Please use the command/flag for AT tokens instead.
```
I think `johns_first_ATtoken` is an ATtoken since the `token list -a | grep johns_first_ATtoken` command outputs it.

**Comment by d5000** [comment]
Fixed in commit afc3af9. This was a small and obvious bug and does not need testing (I've already pre-tested it), issue can be closed.
