### ISSUE TITLE
Token show with -i and -s flag doesn't show the P2TH address

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#219]
I've just run `token show conflicting -i -s` and got the same output of the `token show conflicting -i`, i.e. without the P2TH address.
The `token show conflicting -r -s` works as expected.

**Comment by d5000** [comment]
Fixed in 253f097. Very obvious bug, doesn't need testing, was a side effect when I added the "beautified" mode.

**Comment by buhtignew** [comment]
It works, closing.
