### ISSUE TITLE
The true sender

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#222]
While I was testing for the issue #221 I've seen that if I run `slimcoind gettransaction 76693fc329ec40bcb40d89590c2942ed2539e90e10691bf00bf87ae34c28a230` I'll get the following output:
```
{
    "amount" : 0.00000000,
    "fee" : -0.14000000,
    "confirmations" : 138529,
    "blockhash" : "00000030c4b4023db033a6bf9fd4df5f7f254282dc5738adb43032798b290182",
    "blockindex" : 8,
    "txid" : "76693fc329ec40bcb40d89590c2942ed2539e90e10691bf00bf87ae34c28a230",
    "time" : 1720640194,
    "details" : [
        {
            "account" : "",
            "address" : "n3MtPoPaAREU5GEhAErBPuju83bVog2opz",
            "category" : "send",
            "amount" : -4.00000000,
            "fee" : -0.14000000
        },
        {
            "account" : "",
            "address" : "n3MtPoPaAREU5GEhAErBPuju83bVog2opz",
            "category" : "receive",
            "amount" : 4.00000000
        }
    ]
}
```
Which looks a bit strange to me if I compare this output with what I assume to be the correspondent command in `pacli`, i.e. `pacli transaction show 76693fc329ec40bcb40d89590c2942ed2539e90e10691bf00bf87ae34c28a230 -s`, which outputs as following:
```
{
    'inputs': [
        {'sender': ['n1UYM67wYEveBzUV7b2Di1Jb9tUXTq75Fp'], 'value': 0.01},
        {'sender': ['miHhMLaMWubq4Wx6SdTEqZcUHEGp8RKMZt'], 'value': 0.01},
        {'sender': ['mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn'], 'value': 0.01},
        {'sender': ['miHhMLaMWubq4Wx6SdTEqZcUHEGp8RKMZt'], 'value': 0.01},
        {'sender': ['mguM6Xso6UEVT8uPYGnFMw9aPBZ2vtRKoH'], 'value': 0.01},
        {'sender': ['mqZ5nqs6bpaAqEoEV9jVFfwsM3hBZD4C3J'], 'value': 0.01},
        {'sender': ['n1WEs2vcEbXFQWe6GtsFgHfQmzavHVYMi4'], 'value': 0.01},
        {'sender': ['mtvQZrb9BC8HFtXe87Ev5PEUeA1cSvP211'], 'value': 0.01},
        {'sender': ['mvuMyLkLkYKtnq3DkPY6Xe91AYthEGcfym'], 'value': 0.01},
        {'sender': ['mqnBdCH2cuoSiQWjKoEZHfov77bzrpmtNX'], 'value': 0.01},
        {'sender': ['mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mtvQZrb9BC8HFtXe87Ev5PEUeA1cSvP211'], 'value': 0.01},
        {'sender': ['mtvQZrb9BC8HFtXe87Ev5PEUeA1cSvP211'], 'value': 0.01},
        {'sender': ['mzP9BNtqjSNq2rJ58w8GpQNnez38NGagsU'], 'value': 0.01},
        {'sender': ['mguM6Xso6UEVT8uPYGnFMw9aPBZ2vtRKoH'], 'value': 0.01},
        {'sender': ['mqnBdCH2cuoSiQWjKoEZHfov77bzrpmtNX'], 'value': 0.01},
        {'sender': ['mwutmXuJEzDvfs59nKY47Unm3M8cszxhf9'], 'value': 0.01},
        {'sender': ['mxasNazVpdfTmjQcedfxtHQtb3NXKVGEzh'], 'value': 0.01},
        {'sender': ['moDgh2HgPZKWpFrNesC4QVBzvBrV79p9pA'], 'value': 0.01},
        {'sender': ['miHhMLaMWubq4Wx6SdTEqZcUHEGp8RKMZt'], 'value': 0.01},
        {'sender': ['mksAeTpYqAvyn7W5EFMeoDghSAPSYi5y3g'], 'value': 0.011457},
        {'sender': ['mtvQZrb9BC8HFtXe87Ev5PEUeA1cSvP211'], 'value': 0.01},
        {'sender': ['mtvQZrb9BC8HFtXe87Ev5PEUeA1cSvP211'], 'value': 0.01},
        {'sender': ['mxfu9BNbsaECVVBRiqzavcvp6xhB2cz9r8'], 'value': 0.01},
        {'sender': ['mskwPWmHNAV2yfKPDCs4Yt6WvSpfGbA64e'], 'value': 0.01},
        {'sender': ['mzP9BNtqjSNq2rJ58w8GpQNnez38NGagsU'], 'value': 0.01},
        {'sender': ['mxfu9BNbsaECVVBRiqzavcvp6xhB2cz9r8'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mgGt189MMVH4FPMYCDZVN6DczsAQFSAmB2'], 'value': 0.01},
        {'sender': ['n4AoPomtAQRxsTc2TDMFMsP2PonhZ2vVAz'], 'value': 0.01},
        {'sender': ['miHhMLaMWubq4Wx6SdTEqZcUHEGp8RKMZt'], 'value': 0.01},
        {'sender': ['mz6HENDiSFPYqsi7wDZ33p5jt7j9LFo6qr'], 'value': 0.01},
        {'sender': ['mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn'], 'value': 0.01},
        {'sender': ['mzP9BNtqjSNq2rJ58w8GpQNnez38NGagsU'], 'value': 0.01},
        {'sender': ['miHhMLaMWubq4Wx6SdTEqZcUHEGp8RKMZt'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mxTq1JuXLMZjaKA8LkdySk3sMwhRz4FEG2'], 'value': 0.01},
        {'sender': ['mwLKewF56R8Rje2tAuQRJzDxS9XC1a1q23'], 'value': 0.01},
        {'sender': ['mmjaHuS1kTRMFJaTJqYMjdmF18n36eXHfD'], 'value': 0.01},
        {'sender': ['mtvQZrb9BC8HFtXe87Ev5PEUeA1cSvP211'], 'value': 0.01},
        {'sender': ['mvuMyLkLkYKtnq3DkPY6Xe91AYthEGcfym'], 'value': 0.01},
        {'sender': ['mxTq1JuXLMZjaKA8LkdySk3sMwhRz4FEG2'], 'value': 0.01},
        {'sender': ['myHPHhnncUaiFQGqN1FK2qFtwcfPE4Bkqc'], 'value': 0.01},
        {'sender': ['mx6Dqj2GK5eco5ZMpisgigNy9cTjqsaY6Q'], 'value': 0.010782},
        {'sender': ['n1WEs2vcEbXFQWe6GtsFgHfQmzavHVYMi4'], 'value': 0.01},
        {'sender': ['mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['miHhMLaMWubq4Wx6SdTEqZcUHEGp8RKMZt'], 'value': 0.01},
        {'sender': ['n1WEs2vcEbXFQWe6GtsFgHfQmzavHVYMi4'], 'value': 0.01},
        {'sender': ['mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mtvQZrb9BC8HFtXe87Ev5PEUeA1cSvP211'], 'value': 0.01},
        {'sender': ['myKpK8viS9k8JSWEA9syitxLJUTqdSeSvr'], 'value': 0.01},
        {'sender': ['mvuMyLkLkYKtnq3DkPY6Xe91AYthEGcfym'], 'value': 0.01},
        {'sender': ['n1WEs2vcEbXFQWe6GtsFgHfQmzavHVYMi4'], 'value': 0.01},
        {'sender': ['mguM6Xso6UEVT8uPYGnFMw9aPBZ2vtRKoH'], 'value': 0.01},
        {'sender': ['mvuMyLkLkYKtnq3DkPY6Xe91AYthEGcfym'], 'value': 0.01},
        {'sender': ['mgLyx4nNSPjcimazmo5U2Z8khUiRZWq5hn'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mixcqdAy4aFtuBV7uRebqBTjiFWCcS4UEp'], 'value': 0.01},
        {'sender': ['miHhMLaMWubq4Wx6SdTEqZcUHEGp8RKMZt'], 'value': 0.01},
        {'sender': ['mmjaHuS1kTRMFJaTJqYMjdmF18n36eXHfD'], 'value': 0.01},
        {'sender': ['myu48LbhEumui6yMkdD5DgYYf7STgEtF7Y'], 'value': 3.33},
        {'sender': ['moDgh2HgPZKWpFrNesC4QVBzvBrV79p9pA'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mtvQZrb9BC8HFtXe87Ev5PEUeA1cSvP211'], 'value': 0.01},
        {'sender': ['mpF9FcfSps5jPSG2vDdGVF883xNFez1UGT'], 'value': 0.01},
        {'sender': ['mguM6Xso6UEVT8uPYGnFMw9aPBZ2vtRKoH'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mmjaHuS1kTRMFJaTJqYMjdmF18n36eXHfD'], 'value': 0.01},
        {'sender': ['mvqixcgHjARgA1gPjUFNNSq3CdKy9BmvvA'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['mkwJijAwqXNFcEBxuC93j3Kni43wzXVuik'], 'value': 0.01},
        {'sender': ['n4HXAq2XjJAt4cNRL9gpPjDS7r8hxmghVR'], 'value': 0.01},
        {'sender': ['mvuMyLkLkYKtnq3DkPY6Xe91AYthEGcfym'], 'value': 0.01},
        {'sender': ['mxfu9BNbsaECVVBRiqzavcvp6xhB2cz9r8'], 'value': 0.01},
        {'sender': ['n1WEs2vcEbXFQWe6GtsFgHfQmzavHVYMi4'], 'value': 0.01},
        {'sender': ['mqZ5nqs6bpaAqEoEV9jVFfwsM3hBZD4C3J'], 'value': 0.01},
        {'sender': ['mxTq1JuXLMZjaKA8LkdySk3sMwhRz4FEG2'], 'value': 0.01}
    ],
    'outputs': [
        {
            'receivers': ['myTnp1E8rqYpPbSdwVr9zDFShNGW3z8suX'],
            'value': 0.012239
        },
        {'receivers': ['n3MtPoPaAREU5GEhAErBPuju83bVog2opz'], 'value': 4.0}
    ],
    'blockheight': 486219
}
```
First of all the sender's address mentioned in `slimcoind`'s output is not even present in the `pacli`'s output as sender.

The second strange thing is that `pacli` puts the address `n1UYM67wYEveBzUV7b2Di1Jb9tUXTq75Fp` as the first one, i.e. it considers that address as the main sender, while from the `slimcoind`'s output results that the sender has sent 4 tSLMs (and not 0.01) and as we've discussed in issue #221 the address `n1UYM67wYEveBzUV7b2Di1Jb9tUXTq75Fp` is the change address so it probably should've been chosen as the actual sender (also because `pacli` isn't even able to "see" that address with the `address list` command).

The address that I'd consider more similar to the true sender judging the `pacli`'s output is `myu48LbhEumui6yMkdD5DgYYf7STgEtF7Y` which has sent the majority of the funds during that transaction.

At this point I'm wondering which is the true sender of that transaction, i.e. why `pacli` has decided that particular address to be the sender and not another one (for instance not the `mksAeTpYqAvyn7W5EFMeoDghSAPSYi5y3g` which is also not present in `address list -i` nor `address list -p` outputs on my side so it's presumably a change address too).

However as we've already discussed, this transaction is a kind of anomalous one from the `pacli`'s point of view, because it wasn't created by `pacli` so `pacli` may have difficulties to correctly display and to sort the details of that transaction.
And still that transactions makes part of the outputs of different `pacli`'s commands. 
So I'm wondering how and whether we should limit those results in `pacli`'s outputs or maybe we should warn the users somehow in our documentation or in help provided by different `pacli`'s commands?

**Comment by d5000** [comment]
To see the correct order of the inputs and outputs and thus the "true sender", you need to use `getrawtransaction TXID 1`, not `gettransaction`. `transaction show -s` strictly uses the inputs/outputs order provided by the getrawtransaction command, which is also the order how Slimcoin stores and transmits the transaction. `getrawtransaction` doesn't show the sender addresses though, but the first input of this transaction is a9115695325a7485e7a72882adc6afea7598787840fac93c031ddba73c324002:0, and using `getrawtransaction` at this transaction/output  shows that the "true sender" here is `n1UYM67wYEveBzUV7b2Di1Jb9tUXTq75Fp`, the same address shown at the first rank by `transaction show -s`.

("true sender" only makes sense for token transactions anyway, i.e. if this is a regular Slimcoin transaction then all senders are "real" senders without any hierarchy. This hierarchy is PeerAssets-specific.)

The `gettransaction` output can be  confusing, the address shown at "send" isn't the one which has sent the coins, but actually the address where the coins were sent to. Note that this command can only handle UTXOs related to wallet addresses, and it seems change addresses are excluded, that's why you only see two entries in the "details" item.

**Comment by buhtignew** [comment]
FYI, I've tried to claim tokens from the addresses of the above transaction (`76693fc329ec40bcb40d89590c2942ed2539e90e10691bf00bf87ae34c28a230`) that are not considered mains by `pacli` and had no luck.
While I was able to claim tokens from the main address as if it has sent 4 tSLMs.
So maybe in case of multiple senders as the above one we can shorten the `transaction show 76693fc329ec40bcb40d89590c2942ed2539e90e10691bf00bf87ae34c28a230 -s` output and mention the first address only, because the others are not relevant.
However it probably may cause collisions with the transactions in which there are truly more than one sender and each one is enabled to claim tokens. Or it's not possible to engender such cases?

**Comment by d5000** [comment]
> transaction show 76693fc329ec40bcb40d89590c2942ed2539e90e10691bf00bf87ae34c28a230 -s output and mention the first address only, because the others are not relevant.

No, because this command has multiple uses, not only "see the sender of a burn/gateway tx". For all other uses, all senders are relevant.

Regarding your question about transactions where multiple users can claim, no, they don't exist, this was decided in an earlier discussion and is also consistent with the PeerAssets rule that a token can only have one sender. Every other approach leads to a ton of problems.

> If we decide to accept the idea of the "relevant change addresses" then maybe it can be helpful for the work you are doing right now, because the time to retrieve relevant change addresses may be ways shorter than that to retrieve all the change addresses.

I hope I understand what you mean, but I think there is no way to get an advantage. When searching for change addresses, the algorithm first needs to retrieve all wallet transactions. But once they are retrieved, it doesn't take less time if the algorithm can "filter" them by those which are used as first/"true" senders in burn/gateway transactions.

**Comment by buhtignew** [comment]
Ok, I've got your point.
Closing.
