### ISSUE TITLE
Is it possible to change VALUES of the additional entries visible with `config list -a`?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#23]
I was thinking to try changing values of the additional values mentioned in the `config list -a` output using  `set config` command.
But before I do so were should I change the additional values back in case my `pacli` configuration breaks as result of my tests?

**Comment by d5000** [comment]
These values can't be changed with `config set`. Have just tried it, an error message is shown. They are anyway always loaded again when any command is entered, so I think it would make no sense in changing them.

**Comment by buhtignew** [comment]
Thank you for the info.
