### ISSUE TITLE
`card balances` command

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#27]
I've tested the `card balances` command.

It throws the same error for all the decks except those mentioned [here](https://github.com/slimcoin-project/pacli/issues/26#issue-2141050595):

- TestDeckSLM0222 (160679b53e6785664e75bc3cde5e1c41e88a9aacc8afcc92b641152f51dec959)
- TestToken0522 (e9c2c5bdfdd46372111ec29bf8f30ae39177cf1042ff94b6911e53048c78c0c5)
- DTNewSpecv2 (a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a)
- ATTokenNewSpec2 (fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974)
- PoBSimplest (95b24015ffb46d82015b709d774542fc4a53ccf27f72d973ed3fb18c384a80ca)

However for each of the above deck I'm seeing different quantities of tokens (except for `e9c2c5bdfdd46372111ec29bf8f30ae39177cf1042ff94b6911e53048c78c0c5` for which I'm receiving a void list of balances).
My question is:
Have I participated in testing of all the above decks so far so I have all those different quantities of tokens?

_
I've also noticed a strange thing: if I try to use whatever  casual sequence after `card balance` I'm getting:
```
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 441, in main
    fire.Fire({
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 272, in balances
    cards, deck = self.__list(deckid).values()
                  ^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 258, in __list
    return {'cards': list(cards),
                     ^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pypeerassets/__main__.py", line 228, in find_all_valid_cards
    for card in validate_card_issue_modes(deck.issue_mode, list(unfiltered), provider, deck):
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'issue_mode'
```
(which maybe can be hidden by a more user friendly message), but if if I run `card balances a843d6f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d82` the output is the void list of balances, while the output of `card list a843d6f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d82` is:
```
Error: Label 'a843d6f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d82' not found.
```
What is so special about `a843d6f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d82` line?

I've assumed it's the length but by changing it into `a843d6f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d84` I've got the following results:
- `card list a843d6f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d84` output:
```Error: Label 'a843d6f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d84' not found.```
- `card balances a843d6f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d84` output:
```
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 441, in main
    fire.Fire({
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 272, in balances
    cards, deck = self.__list(deckid).values()
                  ^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 258, in __list
    return {'cards': list(cards),
                     ^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pypeerassets/__main__.py", line 228, in find_all_valid_cards
    for card in validate_card_issue_modes(deck.issue_mode, list(unfiltered), provider, deck):
                                          ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'issue_mode'
```
Which is different from the former results.

**Comment by d5000** [comment]
For this issue the same thing applies than for #26 : please wait with the testing of `card` and `deck` commands (and additonally `proposal`, `donation`, `pobtoken` and `token` commands) until issue #5 is solved.

Nevertheless some answers I can already give:

>  Have I participated in testing of all the above decks so far so I have all those different quantities of tokens?

No, this commands hows all balances of all holders of the token (mostly it should be my addresses).

>  I've also noticed a strange thing: if I try to use whatever casual sequence after card balance I'm getting: [error]

Yes, `card balances` is still an unmodified vanilla command and does only support deck IDs, not labels. I'm however planning to integrate the `token` commands into the `card` class (there are only 2 left after the heavy modifications I made in December), and the vanilla command would then become only one of the options. It would then also support labels and I could also add better error messages.

I did want to change this earlier so you don't get confused by this command, but forgot about it :( So testing `card balances` currently in general doesn't make much sense.

> a843d6f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d82

You're right that it's related to its length. The command `card list` is a modified command and does admit labels, it checks the txid if it's in correct format (64 characters). If not, it assumes it's a label, and if it's not found, then the error you displayed is shown.

You're however correct, with the second version (replacing last 2 by 4) this error is thrown. I don't know if this is important enough to investigate as the final command will check the length, just like `card list`.

**Comment by buhtignew** [comment]
I've tested `card balances 160679b53e6785664e75bc3cde5e1c41e88a9aacc8afcc92b641152f51dec959` (not initiated deck on my side), ` card balances DTNewSpecv2`, `card balances a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a` (the same initiated deck) and got the following message: `Error: No valid address string or non-existing label in the extended configuration file.`
What am I doing wrong? (I was testing the following usage mode:  `pacli card balances DECK [ADDRESS|-w]`).

**Comment by d5000** [comment]
I finally looked into this. No, it seems it's not a bug, but a behavior which can be easily improved.

In the version you tested, `-w` or an address were mandatory, because otherwise it would fallback to another usage mode expecting an address, not a deck. Recognizing the deck would not help.

So I changed some of the flag keywords to make the following mode possible:

`pacli card balances [ADDRESS] -t DECK [-w]`

(the `-t` is short for `--tokendeck`. "deck" wasn't possible because it conflicts with "debug".)

The keywords changed in the following way (to allow short single-letter flags):
`token_type` -> `category`
`cardholders` -> `owners`
`only_labels` -> `labels`

The docstring has been updated to reflect these changes. I think it's more user friendly this way.

Will test all modes with the new flags and then upload commit.

**Comment by buhtignew** [comment]
On my side it seems like `card balances` command requires about 3 minutes to provide an output. Would it make sense to issue a warning, so the user knows the program hasn't stuck?

**Comment by d5000** [comment]
I'm not so much a friend of cluttering the output with warnings but in this case I agree and have added a message (token balances are among the most time-consuming commands). It can of course be overridden with `-q`.

The `-w` option (without `-a`) is quicker because it only checks two decks (default PoB and dPoD) for balances. Most other variants check all initialized decks and thus take some time.

Due to the long time this command takes, I changed the standard behaviour of the single-address mode (without `-w`) so it shows only the default PoB and/or PoD tokens. To see all decks you now have to enter always `-a`. Do you think this is better?

I've also catched the KeyError properly so it shows the "General Error ..." screen indicating to initialize the deck, and also catched the error of issue #76.

Commit: df47e41

**Comment by buhtignew** [comment]
All mentioned in your previous post works fine now.

Maybe we should close this issue so I'll open other smaller ones if needed.

**Comment by buhtignew** [comment]
I'm closing this. We can open smaller issues if necessary.
