### ISSUE TITLE
transaction show command with label

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#3]
I've created a label for one of my transactions using the following command: `transaction set_utxo trx_label 00fd9b41a42cd8c9c78ea20d1e3a466de07147e4c1ff0119608239c0583ada5d`.

I'm able to see is using `transaction list_utxos`, here is my output:

`{
    'trx_label': '00fd9b41a42cd8c9c78ea20d1e3a466de07147e4c1ff0119608239c0583ada5d:None'
}
`

But if I try to run `transaction show trx_label` command I'm getting the _No transaction with this label or TXID was stored._ output, while the `transaction show trx_label --structure` command reports: _Error: Transaction does not exist or is corrupted._

With the `--silent` flag there is no output at all, thus it's still truly silent :-)

Update: 
I've created a label using `transaction set` command. 

I'm still getting _Error: Transaction does not exist or is corrupted._ output if I run `transaction show` with the label and with the `--structure` flag, but without the  `--structure` flag or with the `--silent` flag my output is the TXID of transaction which should be correct.

Seeing the above:
1) do we really need the `--silent` flag?
2) what is the difference between `transaction set_utxo` and `transaction set` commands?
3) which command is to be used to see the list of labels created with `transaction set` command?
4) maybe we should split the explanation on how the `transaction show` command functions in case of the LABEL and in case of the TXID in the third position (after "transaction" and "set" words), because in case of LABEL the `--structure` flag seems to be mandatory while in case of LABEL it mustn't be used at all. 
5) An other option, if my interpretation in the previous point is correct - wouldn't it make sense to suppress the `--structure` flag and to merge the LABEL/TXID outputs so one would just need to use the `transaction show TXID_OR_LABEL` command?

Update:
Maybe the `--structure` flag should be working in the case of label as well? In such case we need it, but the command is not behaves as expected.

**Comment by d5000** [comment]
I wrote already something about how to improve the `transaction show` command in the [other related issue](https://github.com/slimcoin-project/pacli/issues/2).

Now on to your remaining questions:

> do we really need the --silent flag?

The flag is meant mainly for shell scripts. If a query doesn't have a result, then for this purpose it should return nothing (or an empty dictionary or list) and suppress the error message. I often use scripts for testing of more complex command sequences (like those typical for dPoD tokens) and I think power users will use that option too.

>  what is the difference between transaction set_utxo and transaction set commands?

`transaction set_utxo` is to store a combination of a TXID and an output, while `transaction set'`s purpose is to store a whole transaction hex string. Both are useful for the DEX.

> which command is to be used to see the list of labels created with transaction set command?

`transaction list --named`

>  maybe we should split the explanation on how the transaction show command functions in case of the LABEL and in case of the TXID in the third position (after "transaction" and "set" words), because in case of LABEL the --structure flag seems to be mandatory while in case of LABEL it mustn't be used at all.

See the other issue for an alternative solution.
 
> An other option, if my interpretation in the previous point is correct - wouldn't it make sense to suppress the --structure flag and to merge the LABEL/TXID outputs so one would just need to use the transaction show TXID_OR_LABEL command?

That's very similar to what I proposed as improvement for the other issue - `--structure` should only have to be entered if the user wants to see the structure of a labeled transaction, and not the tx itself, in all cases where the label doesn't exist and a TXID is meant, then it should be automatically be assumed. If you'd be fine with this I'll implement that.

**Comment by buhtignew** [comment]
> transaction set_utxo is to store a combination of a TXID and an output number (vout), while transaction set's purpose is to store a whole transaction hex string. Both are useful for the DEX.

What I was trying to understand is the connection between them, since the label created with `set_utxo` is not visible `transaction show` command.
Are they stored in two different places?

**Comment by buhtignew** [comment]
>>which command is to be used to see the list of labels created with transaction set command?

>transaction list --named

Thank you very much I've overlooked it, I was looking for it in the list of flags, while the list of flags were in reality "the list of all the other flags" :-)

**Comment by d5000** [comment]
> What I was trying to understand is the connection between them, since the label created with `set_utxo` is not visible while using `transaction show` as well as `transaction list --named` commands. Are they stored in two different places?

Yes - utxos have an own category in the extended config file.

> If the --silent flag is useful for the power users for the mere fact of not outputting anything maybe we'll need to make the selection of commands that will be necessary for the beginner users, then another for the intermediate, for instance, and then for the advanced ones (might they need it) on the level of a kind of manual, thus the beginners and the intermediate won't have the need to look into --help to know what to use.

The manuals in the wiki (which mostly cover beginner to intermediate level) will be updated once the commands are set in stone. I'm not willing to write everything several times. The docstrings (--help) are meant for advanced user as well as for a quick reference.

**Comment by buhtignew** [comment]
> The manuals in the wiki (which mostly cover beginner to intermediate level) will be updated once the commands are set in stone. I'm not willing to write everything several times. The docstrings (--help) are meant for advanced user as well as for a quick reference.

Of course! :-)

**Comment by d5000** [comment]
> How should I do to list them?

`pacli transaction list_utxos`

Will of course only output something if you have stored an UTXO.

**Comment by buhtignew** [comment]
> Will of course only output something if you have stored an UTXO.

Oh, of course!
I'm closing this discussion.
