### ISSUE TITLE
A transaction with many senders

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#34]
While running different tests I've discovered a transaction that has a lot of senders.
Here is the output of `transaction show f8ae0dbca3a487bb8ff4ff4d8618591927e2888c71b5f292b0a6b66d0319522c -s`: [transaction_show.txt](https://github.com/slimcoin-project/pacli/files/14402092/transaction_show.txt).
What is it?

UPDATE: one of receivers is my address, but the senders are not, at least not all of them.

**Comment by d5000** [comment]
This was probably me (or you?) consolidating funds in ancient times (block height 21000 or so) :) 
Perhaps also I sent you testnet coins? I'm not really eager to check the senders now ... but it looks like generated coins.

The 0.01 should be the change.

Please close if you have no more related questions :)
