### ISSUE TITLE
Yet another question about --param flag in transaction list

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#35]
I apologize since I remember that we've already spoken about, but I'm not able to remember the answer to the question.

What are the parameters that can be used with the `-p` flag in `transaction list`?

There is an address I have with just one transaction on it, which is comfortable for testing.
So I've run `transaction list mtMGkB2mVxzPNZCWHruRmG1SmsSJBtyCUD -a` using that address thinking that the parameters that would be outputted with that command are the parameters to use with the `--param` flag, but got no luck with none of the following commands:
`transaction list mtMGkB2mVxzPNZCWHruRmG1SmsSJBtyCUD -p value`
`transaction list mtMGkB2mVxzPNZCWHruRmG1SmsSJBtyCUD -p blockheight`
`transaction list mtMGkB2mVxzPNZCWHruRmG1SmsSJBtyCUD -p hex`
`transaction list mtMGkB2mVxzPNZCWHruRmG1SmsSJBtyCUD -p IsBurnTx`
`transaction list mtMGkB2mVxzPNZCWHruRmG1SmsSJBtyCUD -p asm`

What is it that I'm doing wrong here?

**Comment by d5000** [comment]
The parameters you can use are the first level values in the JSON string which is output as a result by the different modes.

For example, in the advanced mode (`-a`) it's all first-level variables in the JSON you get when you call `slimcoind getrawtransaction TXID 1`. In this case: "hex", "txid", "version", "time", "locktime", "IsBurnTx", "vin", "vout", "blockhash", "confirmations", "time" and "blocktime".

Your error was probably that you omitted `-a` in the examples. The regular (not advanced) mode has much less parameters you can use ("txid", "tx_type", "confirmations", "value_sent", "value_received"). Simply look at the dictionaries you get with the different modes of `transaction list` and use one of its keys with the "param" option.

Please close if this answers your question.

It was however good that you mentioned this option because I found a small bug and fixed it in commit c36ba5e.

**Comment by buhtignew** [comment]
The --param list is different for each mode and for someone who is not used to the pacli terminology it can be tricky to get the meaning of the explanation in help.

Would it make sense to list the possible parameters for each mode if no parameter is included after the `-p` flag? Maybe we can treat the `-p` flag without the text afterwards as an error so the output would be: `Error: no parameter mentioned after the -p flag, the possible parameters in this case are the following:`

**Comment by d5000** [comment]
To be honest, this is an option I made mainly for myself for testing. It is very technical. So I don't think it will be used much (and almost never by average users). I can see if I can improve the help a bit but I don't want to lose much time on it, and a list of possible parameters would have to be maintained.

The error message suggestion however is fine, I'll implement it.

**Comment by buhtignew** [comment]
We can let it as it is, but it's a bit difficult for me to test them

> and a list of possible parameters would have to be maintained.

My idea here is to avoid maintaining the list of the parameters extracting them automatically from the `transaction list [flags without -p]` output, thus there would be any need to explain what are the possible parameters in each case.

**Comment by d5000** [comment]
I have found a way to do like you suggested. If a parameter is not found, a list is generated from the first transaction shown. Take however into account that this may not be the complete list of parameters, thus the "some" in the message. This would even be the case if we analyzed the whole list of transactions, so it can't be completely solved this way. But as a hint it's ok I think.

Can be closed if it works as intended.

**Comment by buhtignew** [comment]
I'm re-reading my message and it seems like it was not that clear what I meant with `transaction list [flags without -p]`. The actual meaning was `transaction list [different flags] -p without parameter afterwards`. However you've been able to understand my idea.
Incredible! 8-)
But why is it that there is no way to extract all the possible parameters for any mode?
"Some" word in the output is a kind of frustrating. Where the user is supposed to get the parameters from? If he'd be able to why is it that the code fails?
For instance in my `transaction list` output I was able to see that there is `value sent` parameter not included in the corresponding `-p without parameter` output.
_
I'd also suggest us to slightly change the output of the `transaction list -p`, editing "Parameter 'True' does not exist in the listed transactions of this mode." into something "No parameter included after the -p flag" or  "No valid parameter included after the -p flag", to improve the understanding of the issue for the user.

**Comment by d5000** [comment]
Additional branch was added to filter out the "True" value (i.e. when no parameter is given) to output a better message.

The reason that a complete auto-generation is not possible in this fashion is that the dictionary keys (the "parameters") can change with each transaction, i.e. not the whole set is shown always. Even if we extract the dictionaries of all transactions of the current list it can happen that the list is not complete.

I'm putting this on my TODO list for later. I have an idea how to solve it, but this will need some deeper changes, and I don't consider this function very important.

Please let's stay a bit more focused to the general goal of Pacli, take into account that here we are building a tool to manage and transfer tokens, not a swiss army knife to analyze transactions in depth. I'm sometimes thinking that I should never have added that many modes to `transaction list`. But now that they are there I'm not willing to trash them either as many are useful for debugging. But we don't need to make all of them ultra-easy to use for non-techies.
