### ISSUE TITLE
transaction show command with -s flag output for receive transactions

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#39]
I've tested the following command `transaction show 896c9152e94ef2e747beae168117ce822c007856cd552d6b16ec9cf91d5b4eb5 -s` (for the receive transaction I've found in `transaction list -w` output) and got the following:
```
{
    'inputs': [],
    'outputs': [
        {'receivers': ['mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35'], 'value': 175.5}
    ],
    'blockheight': 203615
}
```
Thus the sender's address is hidden. Would it make sense to make it explicit?

**Comment by d5000** [comment]
This is a coinbase transaction (transaction with mined coins). It does not have a "sender", so nothing can be made "explicit".

You can close this if it answers your question.

**Comment by buhtignew** [comment]
Oh, that's interesting, so those coins were mined?

Would it make sense to make it explicit in the `transaction show [transaction_id] -s` output.
I mean instead of `'inputs': [],` to show something like `'inputs': [coin_base_transaction],`?

**Comment by d5000** [comment]
Yes, these are mined coins (or PoS/PoB minted).

I have thought about making the "coinbase" explicit, but there are other commands depending on this dictionary structure which would have to be modified too in this case. It's not a change of only a few lines. Maybe I can later add a "user-friendlier" printout view but this has very low priority for me at the moment.

**Comment by buhtignew** [comment]
I've got it and I think we can close this issue for now.
