### ISSUE TITLE
The apparently not working transaction mentioned earlier

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#4]
Just for your info, as reply to the following: https://www.reddit.com/r/slimcoin/comments/18asmhk/comment/ki0vx62/?utm_source=share&utm_medium=web2x&context=3 and specifically to 

> It seems also that your TXID doesn't exist, I can't see it with slimcoind getrawtransaction.

In fact I've made a wrong copy-paste of the transaction id earlier, the right one was just on character longer and with that one the command `transaction show` with the `--structure` flag functions correctly.

**Comment by d5000** [comment]
Ok thanks for the info, I assumed something like this :)
