### ISSUE TITLE
P2TH fees

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#40]
[Here](https://github.com/slimcoin-project/pacli/issues/5#issuecomment-1968958446) you've mentioned that  _P2TH fees can be spent by anyone_. Does it mean that someone who doesn't have a slimcoin can import those addresses into his wallet and move them to his private address get some profit?

If so it can also be an interesting feature of SLM, kind of involuntary donations - there are many people out there begging for coins and we have that feature already included for those in need. If presented in a right manner it can attract people interested in increasing the SLM/dPoD token transactions to get their free coins, but the increase of activity on the blockchain should be related to the increase of the value of the coin.

Have I understood it right?

**Comment by d5000** [comment]
> Does it mean that someone who doesn't have a slimcoin can import those addresses into his wallet and move them to his private address get some profit?

Yes, and in fact he only has to initialize the related decks and he could already spend them.

> If so it can also be an interesting feature of SLM

Interesting thought :)

Yes, it's like a kind of lottery at this moment, in theory everybody can collect these fees. However, I can imagine probably "professional" p2th-fee-collectors could rapidly automate the fee collection once SLM increases in value. This would be something similar to MEV collection in Ethereum.

But while SLM stays under the radar and is low valued there could be a time window for this to work in the way you described.

Once we have the upgraded client however, I'd be in favor to change the scheme - at least to reduce the minimum P2TH amount to something close to 1 "slimtoshi" which would not be worth to be collected.
