### ISSUE TITLE
Compatibility mode

### ISSUE THREAD

**Issue by d5000** [slimcoin-project/pacli#41]
I've implemented the "compatibility mode" I announced in commit 3df2457.

It affects currently the following commands: `config set` and `deck list`. The way it affects these commands is shown in the docstrings of the commands.

Later `card balances` and `card transfer` will be added, so these commands should still not be tested.

Compatibility mode can be set to true with the following command:

`pacli config set True -c`

and disabled with

`pacli config set False -c`

Edit: Small clarification: The compatibility mode setting is stored in pacli.conf, but it is not set by the default pacli startup code. This is not needed because the setting is not crucial for pacli's working. So if you still do not have this setting in pacli.conf (it will not be created by an upgrade, but it will be created by a new installation, because its absence can lead to errors), it can simply be added by one of the above commands, i.e. setting it to True or False. I created a specific flag for this just to be able to ignore the "normal policy" of not allowing new settings/labels in this file.

So if you get an error somewhere mentioning "Settings.compatibility_mode", simply use one of the above commands.

**Comment by buhtignew** [comment]
This works, thank you very much!

**Comment by d5000** [comment]
Two commands have been added to the compatibilty mode: `card balances` and `card transfer`.

They work now like `token balances` and `token transfer` before if the compatibility mode is not set. This allowed me to remove the Token class which only contained these two commands.

If the compatibility mode is set to True and the commands are used without flags, they work like the old "vanilla" commands.

Commit: 17ad44d

If there are no problems with this, the issue can be closed.

**Comment by buhtignew** [comment]
We can close this, when I'll begin testing this part I'll be opening short specific issues for each case if any.
