### ISSUE TITLE
How to set an address as main?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#44]
Sounds ridiculous, but it seems like I'm not able to remember anymore how to set an address as main.

I thought it was `address set ADDRESS`, but I've got `Error: Invalid address or private key.` using that command.

Then I've tried `address set --address ADDRESS` and got `ERROR: The function received no value for the required argument: label`.

The only way I've found is to use a label. What I'm missing here?

**Comment by d5000** [comment]
This was indeed not implemented still, the command was always expecting a label. I've implemented it now with `-a ADDRESS` in commit 744f22a. In the same commit I changed `--account` flag into `--to_account / -t` to leave the `-a` for this purpose.

**Comment by buhtignew** [comment]
This works great.
We can close this issue.
