### ISSUE TITLE
Transaction list command with the -k and -n flag

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#46]
I've run `transaction list -n -k` and got the same output of `transaction list -n`.

The `-k` flag description states as following: `Use an address/label stored in the keyring`, but are there addresses that are specifically stored in the keyring? I thought only the labels where. Maybe we should edit it into `Use a label stored in the keyring`?

_
Also output of the `transaction list [ADDRESS] -n` is the same as that of `transaction list -n`.

**Comment by d5000** [comment]
> The -k flag description states as following: Use an address/label stored in the keyring, but are there addresses that are specifically stored in the keyring? I thought only the labels where. Maybe we should edit it into Use a label stored in the keyring?

There can be addresses which are stored only in the keyring, not in the wallet, so the flag description is correct. But I think I get what you mean so I changed it into "a label of an address stored in the keyring". Will be uploaded in the next substantial commit.

>  Also output of the transaction list [ADDRESS] -n is the same as that of transaction list -n.

ADDRESS is not mentioned in the help file for this option so I see no need to change anything.

I'm closing.

**Comment by buhtignew** [comment]
What I was wondering here is that at the moment I have only 3 named transaction, but what if I had hundreds of them? 
Wouldn't it make sense to have them sorted by the relative address as well?

**Comment by d5000** [comment]
I think you meant sorting by label. Yes, that makes sense. I've just implemented that for all lists of this type. Commit: 32938f3

**Comment by buhtignew** [comment]
I think I've formulated it wrong.
Instead of "sorting" I meant to have the possibility to output the transaction label that corresponds to an address.
We are already outputting transactions of an address, should someone have hundreds of labeled transactions would it have sense to output those of a specific address only?

**Comment by d5000** [comment]
Why should you label hundreds of transactions?
I'm not accepting feature requests anymore unless for _very_ good reasons :) (No time, sorry.)

**Comment by buhtignew** [comment]
Agreed.

**Comment by buhtignew** [comment]
If we see that it's necessary we can implement it later on, can't we?

**Comment by d5000** [comment]
Of course. I'm closing this, reopen if there are open questions to the command.
