### ISSUE TITLE
Transaction list output for the addresses which got no transactions.

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#48]
The output `transaction list [ADDRESS]` is the following at the moment `Searching transactions (this can take several minutes) ...`.
Would it make sense to add a courtesy message: "No transaction on this address yet", for instance?

**Comment by d5000** [comment]
Done. I actually thought I did that but it seems not.

All the small changes in the help strings and this one are bundled in commit 0f405b8.

(I've closed the issues which only needed a small help string fix, as these don't need to be tested.)

**Comment by buhtignew** [comment]
Works as expected. I think we can close this issue.
