### ISSUE TITLE
deck storeblocks

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#52]
I'm beginning to have a look into the new feature described in issue #50 
It will help me also to accomplish the `transaction list` command tests.
I'd like to ask whether it make sense to shorten the `deck storeblocks` into `deck store`?
Would it conflict with something else or make the understanding of command less obvious?

**Comment by d5000** [comment]
`deck store` is a bit too unspecific, because you're not storing the decks. It could be confused with `deck set`.

I'm open for other suggestions though, I'm myself not entirely happy with that word.

**Comment by buhtignew** [comment]
What about `deck cache`?

**Comment by d5000** [comment]
Still a bit unspecific, but much better. If we find nothing better I'll use this one.

**Comment by buhtignew** [comment]
Would you please describe with as much words as necessary the specific meaning you'd like to convey that command? That may help me finding the right word for it.

**Comment by d5000** [comment]
I think a good conceptual description would be: "store the block heights when a deck's state changes". Something like "cachestate" or "storestate" so would be possible but if you find a single word even better.

**Comment by buhtignew** [comment]
What about collect, garner, accumulate (or cumulate), stock, or stockpile?

**Comment by d5000** [comment]
Thank you for your ideas. Have today thought a bit about them.

`stockpile` is good I think, but it's almost as long as something like `storestate` or `cachestate` which would be more precise. 

On the other hand `stock` alone would be shorter, but I'm unsure if it's used in this way in English.

I found also `stash` which is also used by git to "cache" a state. Again, as I'm not an english native speaker: do you think `stash` could work better than `cache`? I associate "caches" with temporary storage, while the command stores the blockheights permanently.

**Comment by buhtignew** [comment]
I'm not sure about stash, because it means "to store in a usually secret place for future use". Since blocklocator.json is not meant to be hidden, maybe this world is not that appropriate.

**Comment by d5000** [comment]
I think in Git it doesn't have this "secret" meaning. Anyway, don't want to make you lose time on this, so I'll stay for now with "cache" and close.

**Comment by buhtignew** [comment]
We can close this, I remember to test it. If there is any issue I'll open another issue or reopen this one.
