### ISSUE TITLE
deck help content

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#53]
I'm seeing the following two section in the `deck` help:

```
NAME
    pacli deck - @classmethod def list(self): '''find all valid decks and list them.'''
```
and 

```
DESCRIPTION
    decks = pa.find_all_valid_decks(provider, Settings.deck_version,
                                    Settings.production)

    print_deck_list(decks)
```
The meaning is not that obvious for me.
Is it the intended form of those sections or it's just a sketch waiting to be refined later on?

**Comment by d5000** [comment]
This is an auto-generated docstring by Fire. If it has a fast solution, I'll give some rudimentary info but I think this is not priority, users should use the help options with the commands.

**Comment by buhtignew** [comment]
Maybe:
```
NAME
 
pacli deck 

```

```
DESCRIPTION

a group of commands to manage the decks
```
Can it work for you?

**Comment by d5000** [comment]
I've found the problem - I had commented out a method of the original Deck class and Fire interpreted this as a docstring.

Will be uploaded with next commit. Can be closed if solved - I'll revise all other class docstrings to avoid this to happen in another place.
