### ISSUE TITLE
transaction list [ADDRESS] with -b|-g|-c flags

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#55]
I know that the transaction list can't be used like this: `transaction list [ADDRESS] -b|-g|-c` and there is no such usage mode in the help description either.

Still it's possible a user thinks he can have the burn, gateway or claim transaction list for a specific address.

Maybe we could change the error message outputted in such a case from `Error: Label [ADDRESS_OR_ADDRESS_LABEL] not found.` to `Error: Deck label [ADDRESS_OR_ADDRESS_LABEL] not found.`?

UPDATE: We can also specify it in the help for the -b, -g, and -c flag that they are only used with decks not with addresses.

Or it would make sense to consider providing people with the address specific burn, gateway and claim transaction list?

**Comment by d5000** [comment]
Oh, here I had forgot the ADDRESS parameter in the help. Actually this "filter" exists for these modes. I've added them (commit 8527e73 includes also the fix for `-b` flag).

The usage is actually: `transaction list DECK ADDRESS -b|-g`

A "problem" is however that you can't use the ADDRESS parameter without DECK at this moment. I'll think about a solution.

**Comment by buhtignew** [comment]
I've run `transaction list fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 -u -b -w` and one of the transaction I've got were the following:
```
{
    'txid': '9a930a8d1332a51fa36d21336806afad36f2ff76bf2e568d533fbe3beaf3a458',
    'value': Decimal('2.0'),
    'outputs': [0],
    'height': 169499,
    'sender_label': 'donor_address7',
    'sender_address': 'mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35'
}
```
Then I've run `transaction list fb93ccfb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35 -u -b` and got the following output:
```
Searching transactions (this can take several minutes) ...
Using burn address.
0 unclaimed transactions to mmSLiMCoinTestnetBurnAddress1XU5fu in this wallet.
Showing only transactions sent from the following address: mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP
No matching transactions found.
```

The same for `transaction list fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974  mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35 -g`

What I was doing wrong here?

The `transaction list fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP  -c` command seems to work fine, but I'm using the receivers address, since it's mentioned in `transaction list fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974  -c -w` output.

_
When I run `transaction list   mrnZpB5Wm1FDBBcZ1s1pdPHpQgzaLRteSr  -b` described in the help I'm getting: `Error: Label 'mrnZpB5Wm1FDBBcZ1s1pdPHpQgzaLRteSr' not found.`.

**Comment by d5000** [comment]
First problem: Yep, that's a bug, seems it tries the main address (?). Will fix it ASAP and then post the commit here.

> transaction list   mrnZpB5Wm1FDBBcZ1s1pdPHpQgzaLRteSr  -b

That's actually what I wrote in the last post: entering only the address with `-b` doesn't work, you always need the deck as first positional argument. It's a problem related to the branching structure of the command which is quite complex because the positional arguments can be decks or addresses. I'm sure I can solve it however.

**Comment by buhtignew** [comment]
> seems it tries the main address (?)

Yes, indeed

> That's actually what I wrote in the last post: entering only the address with -b doesn't work, you always need the deck as first positional argument. It's a problem related to the branching structure of the command which is quite complex because the positional arguments can be decks or addresses. I'm sure I can solve it however.

The issue here is the text in help then. There is the following line in the Usage modes: ` pacli transaction list [ADDRESS] -b` that probably should be changed into ` pacli transaction list  [DECK ADDRESS] -b`.

**Comment by d5000** [comment]
I fixed the first bug and figured out a way to use ADDRESS without DECK for the `-b` option without having to change much of the branching structure. By the way I've fixed also a bug in `address set` I stumbled upon.

Commit: 8fea5e1

**Comment by buhtignew** [comment]
Seems to work as expected. But what was the issue with `address set`, would you remind me please, so I test it as well?

**Comment by d5000** [comment]
Wasn't really important - after a recent change in some cases an error message was shown after the label was set correctly. You can simply set any label for any address and if no error shows up then it works as expected.
