### ISSUE TITLE
"unlabeled" label still appears in some output

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#56]
Testing the `transaction list fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 -u -b -w` command I've found a transaction that has the following outlook:
```
{
    'txid': 'b8f04a83ede9a21e7df2071513019c598c7ed7d857a75a67a3165a1a57f64ff3',
    'value': Decimal('1.0'),
    'outputs': [0],
    'height': 203615,
    'sender_label': '(unlabeled8)',
    'sender_address': 'mixcqdAy4aFtuBV7uRebqBTjiFWCcS4UEp'
}
```
Would it make sense to output the void string for the the 'sender_label' in such cases?

**Comment by d5000** [comment]
Fixed in commit 718af3b.
