### ISSUE TITLE
Transaction list with -v flag

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#60]
I've tested `transaction list -v` command and discovered that it outputs the same number of transactions as `transaction list` command.
Is it intended behavior?

**Comment by d5000** [comment]
No, this was an oversight, I'd implemented it only for `-x`. Thanks for reporting.

As it was a very easy addition for the standard mode (with or without `-w`) I added it. I get now significantly less transactions without the `-w` flag (>6000 with coinbase txes, 558 without). For the `-b`, `-g`, `-n` and `-c` modes it makes no sense so it won't be included in these modes. 

Commit: 98cb9bf

Can be closed if solved.
