### ISSUE TITLE
A question about the meaning of transaction list's -b flag.

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#62]
In the issue #61 I was trying to understand whether I've made some burning transaction from my main address `mx5MdsenFDZufFuwT9ND7BKQBzS4Hy9YUP`. So I've run `transaction list -b` command and got the following list:
```
{
    'txid': '02d5137033aa5f16bc212d4107edb175cfe804bf17bab93133fdd151f85efa95',
    'value': Decimal('101.1'),
    'outputs': [0],
    'height': 155569
}
{
    'txid': '389f52840c48ffff88d01323cd92af12e762f0c9ef0bb6771c432c0d0b3d05f1',
    'value': Decimal('10.0'),
    'outputs': [0],
    'height': 157486
}
{
    'txid': '75fbc07c9998bf29642e4b68c772453215364de58800ca9ce10e0b61a520daa9',
    'value': Decimal('123.0'),
    'outputs': [0],
    'height': 156493
}
```

To check whether it's really my main address' transactions and not something else I've run `transaction list mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35 -b` command (using another address I have) and got `Error: Label 'mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35' not found.` So I've remembered what you've wrote [here](https://github.com/slimcoin-project/pacli/issues/55#issuecomment-1995673722): "_entering only the address with -b doesn't work, you always need the deck as first positional argument_" thus I've run `transaction list f7b1af6d565898851878cb13c88bb52996a0a5380c4ea8803c248a69c7d00d82 mskxtnWBJ1bBYZxmHe8rTR5H8ayZEXvG35 -b` and got the same output as reported above.
Hence my question is: how should I interpret the `transaction list -b` output I've got initially?

**Comment by d5000** [comment]
In my installation it works as expected: `-b` alone shows the burn transactions from the main address.

What address is shown behind the message `Showing only transactions sent from the following address:` ?

Has this perhaps been also fixed with the latest fixes? (every commit you update to on March 15 should include it)

**Comment by buhtignew** [comment]
The last update has solved this issue.
