### ISSUE TITLE
An idea on how to hide the error message of address list -k 

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#63]
I've got an idea on how to hide the undesired  message of the `address list -k` command.

I think we've discussed this message many times and I remember that you've qualified it as a WONTFIX.

However I've just run `address list -k 2>/dev/null` and got the normal `address -k` output without the initial message mentioned, for instance, in issue the #47: 
```
/usr/lib/python3.11/site-packages/jeepney/low_level.py:314: ResourceWarning: unclosed <socket.socket fd=8, family=1, type=1, proto=0, raddr=/run/user/1000/bus>
  valtype = parse_signature(list(sig))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Would it make sense to add this hack into the code for the moment?

**Comment by d5000** [comment]
I'm not comfortable with this, because this would suppress other errors.

**Comment by buhtignew** [comment]
It can suppress only this error, i.e. evaluate whether the message is as above if and in such a case suppress, while otherwise output.

**Comment by d5000** [comment]
If you can suppress only this message in the pacli_env code, go ahead. But I categorically oppose to include a "catch all errors" thing in the Python code, and will not waste more time in this.
