### ISSUE TITLE
New deck list mode -s

### ISSUE THREAD

**Issue by d5000** [slimcoin-project/pacli#64]
I have added a very simple mode to `deck list` I felt was necessary: the list of only the "standard", e.g. default PoB and dPoD tokens (those shown in the standard `address list` table). Commit: 35147b1

Mode is called with `deck list -s`.

Previous to this change, `-s` called `--show_p2th` mode. This mode has been renamed to `-o`/`--only_p2th`,, as I didn't find a good synonym for `standard` (and `default` conflicts with `debug`). Docstrings have been changed to reflect this.

Also two small bugs in the same command have been fixed.

Issue can be closed if there are no further questions.

**Comment by buhtignew** [comment]
This work as expected. Very useful feature.
Nothing to discuss further. I'm closing this issue.
