### ISSUE TITLE
The -v flag description in the help of transaction list.

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#66]
I feel we could make the `-v` flag description in `transaction list` help more specific.

It states `Show coinbase transactions (not in combination with -n, -c, -b or -g).`, but maybe it would be more exact to say `Adds the coinbase transactions to the output (not in combination with -n, -c, -b or -g).`?

**Comment by d5000** [comment]
Done & closed, will be uploaded in next commit.
