### ISSUE TITLE
transaction list -x with and without receiver's address

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#67]
Finally I've put my hands on the last part of the `transaction list` command, that with the `-x` flag.

I've begun with testing on the small chunks of the chain in order to get quick results to begin with.

I'm not using locator for the moment, because I'd like to test the original functioning of the command first.

So I've  compared the `transaction list -x -f 396100 -e 396205` and the `transaction list -x mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w -f 396100 -e 396205` outputs and it seems like there are transaction in the later, which are not making part of the former.

For instance the following one: `9d93068617e6fa6eabb9163d50c463496ded30c6c743e5ab9132c1a0d37d05fa`.

Seeing the number of it confirmations I'd say that the command with the address (`transaction list -x mfbn3FPxjUXKGNafLhPa6q5SxATPCUgj8w -f 396100 -e 396205`)  is providing results that are out of the required range.
The only doubt I have with such an assumption is why is it that the results were provided still very quickly if the chain was scanned so deeply? Is it possible that I've still activated locator somehow previously?

**Comment by d5000** [comment]
Seems the same problem like issue #68  - the help docstring was wrong :(   (receiver address comes before the `-x`).

I'll revise the help to see if there are more such errors, to avoid that for the future.

**Comment by buhtignew** [comment]
This is solved.
