### ISSUE TITLE
deck find

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#74]
I've tested `deck find` command and got the following error while I was trying to make a search using the `issue_mode` (`deck find 1` in this specific case) and `number_of_decimals` (`deck find 2`):

```
Traceback (most recent call last):
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 444, in main
    fire.Fire({
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 135, in find
    print_deck_list(
  File "~/.local/lib/python3.11/site-packages/pacli/tui.py", line 40, in print_deck_list
    print_table(
  File "~/.local/lib/python3.11/site-packages/pacli/tui.py", line 16, in print_table
    data = list(data)
           ^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/pacli/__main__.py", line 136, in <genexpr>
    (d for d in decks if key in d.id or (key in d.to_json().values()))
                         ^^^^^^^^^^^
TypeError: 'in <string>' requires string as left operand, not int
```
Is it possible that some flag is missing in the help or there is something else I was doing wrong?

**Comment by buhtignew** [comment]
The error message is gone.

Maybe we can change the help text, to make it more clear the type of results that are being provided.

We can edit: `Find specific deck by key, with key being: <id>, <name>, <issuer>, <issue_mode>, <number_of_decimals>` into `Find specific deck by key, with key being: partial or full deck ID string, exact Global name string or exact Issuer string`.

I'd also suggest us to prevent using this command to the search by <issue_mode> and <number_of_decimals>, because those numbers are so short that all the decks that contain those numbers in their id are also included, which may create misunderstanding for the users.

**Comment by d5000** [comment]
You may perhaps noticed that I don't want to change too much in the vanilla commands. This is to be able to import the upstream changes from the PeerAssets project if they arrive. Replacing them all with "embellished" and improved commands is not my priority at this time, because there are alternatives for most of them.

Editing the help message is ok though, as I have done that several times already ...

**Comment by buhtignew** [comment]
Thank you for the list I think it's quite useful.
What are the command we have that should be in our priority list to test?

**Comment by d5000** [comment]
At this moment, those with most priority are:

- the block locator mechanism (all those mentioned in issue #50) testing should be completed. I'll try to finish the integrity test for the end of the week.
- the remaining non-vanilla commands of the `card` group (`transfer`, `balances` and `list`, some already have threads but I think there were some minor issues remaining)
- all commands related to AT and PoB tokens (`pobtoken` and `attoken` groups)
- next step would be the `dex` group.
- `podtoken`, `proposal` and `donation` groups can wait a bit more. They're already quite well tested though.

**Comment by buhtignew** [comment]
Thank you for the hint.
So we should close this issue?
