### ISSUE TITLE
What block is our test node on?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#82]
My local `slimcoind` is stuck on the block 413183 at least since this morning.
Is the test node we have halted on the same block at the moment?

(We'd need the blockchain to move in order to test the most urgent commands you've mentioned [here](https://github.com/slimcoin-project/pacli/issues/74#issuecomment-2038187797), except the block locator mechanism).

**Comment by d5000** [comment]
It seems so, my nodes are both on this height too. My server node had crashed (probably in the last 3 days) but the test server was disconnected much before so I think that should be the correct block height.

**Comment by buhtignew** [comment]
We are on the same height today as well, then. Probably we need some stronger server to make the blockchain moving forward.

**Comment by d5000** [comment]
Yes that's the problem I briefly mentioned earlier: the server drove the difficulty quite high. We'll have to mine for some time with the home pcs just to find a block it seems ... then it should go faster as SLM's difficulty should react instantly to the long period without blocks, reducing significantly.

**Comment by buhtignew** [comment]
Do you mean mining with CPU or minting with PoB or PoS is fine as well?

**Comment by d5000** [comment]
AFAIK only PoW mining reduces the PoW difficulty. I'm sure that PoS does not because it's difficulty is different, but I'm not totally sure about PoB, because PoB minting uses partly the PoW code and some parameters. I mean to remember (when I looked into this part of the code last time) that the difficulty is however separate.

**Comment by buhtignew** [comment]
I don't really know how to mine. Do you have any experience?

**Comment by d5000** [comment]
Simply enter `slimcoind setgenerate true` after starting slimcoind testnet client. To turn it off again, `slimcoind setgenerate false`.

**Comment by d5000** [comment]
There's not much to know. Simply enter `slimcoind setgenerate true` after starting slimcoind testnet client. You can check with `slimcoind getblockcount` if the blockchain has moved. To turn it off again, `slimcoind setgenerate false`.
