### ISSUE TITLE
Are the burn transactions a subcategory of the gateway transactions?

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#84]
[Here](https://github.com/slimcoin-project/pacli/issues/80#issuecomment-2058252200) you've wrote: _I'm not sure which AT deck I had tested with gateway transactions. I ended up trying it with a PoB deck (fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974) and it worked._
So I've compared `transaction list -b -x -f 156492 -e 156902` and `transaction list fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 -g -x -f 156492 -e 156902` outputs and they were identical except `Using burn address.` line the former had.
Does it looks right to you?
I mean the `transaction list fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 -g -x` (without the address) refers to the main address of the moment as well as `transaction list -b -x`?  And the burn transactions are a subcategory of the gateway transactions?

**Comment by d5000** [comment]
Yes, that looks correct.
Burn transactions can be considered gateway transactions going to SLM's official burn address. The way the burn tokens work is exactly the same than the "normal" AT tokens. There are only some CLI differences: e.g. in the `transaction list` command we don't need to specify the deck if we want to see the burn transactions. The deck in the case of "non-PoB" AT tokens is needed to get the tracked address (for gateway transactions) and for all PoB tokens the burn addres is the same one.

**Comment by buhtignew** [comment]
Everything fine with this then. I'm closing this issue.
