### ISSUE TITLE
Some remark about token transfers command

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#87]
I've re-tested `token transfers` command and has discovered the following:

1) The `-d` flag is considered in conflict with the positional argument Deck, in fact if I run `token  transfers fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 -d`, for instance, I'm getting: 
```
ERROR: The argument '-d' is ambiguous as it could refer to any of the following arguments: ['deck', 'debug']
```
2) There is no difference in output if I run with or without `-d` or `-q` flags.

**Comment by d5000** [comment]
1. Fixed in next update. The `--debug` flag here has no real debugging messages but has the effect that in the case of errors (e.g. the "General error ...") a traceback is shown. This behaviour was implemented also in other commands.

Can be closed.
