### ISSUE TITLE
token balances with the -n and -l flags

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#94]
I've tested `token balances -w -n` and got the following error message:
```
Traceback (most recent call last):
  File "~/.local/bin/pacli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/__main__.py", line 479, in main
    fire.Fire({
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 1180, in balances
    return ei.run_command(self.__balance, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_interface.py", line 33, in run_command
    result = c(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/extended_classes.py", line 1236, in __balance
    return tc.all_balances(address=address, wallet=wallet, keyring=keyring, no_labels=no_labels, only_tokens=True, advanced=advanced, only_labels=labels, deck_type=deck_type, quiet=quiet, debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/pacli/token_commands.py", line 109, in all_balances
    ei.print_default_balances_list(balances, labeldict, decks, network_name=Settings.network, only_tokens=only_tokens)
                                             ^^^^^^^^^
UnboundLocalError: cannot access local variable 'labeldict' where it is not associated with a value
```
The `token balances -w` works fine.
_
The `token balances -w -l` output is the same as `token balances -w`. I was expecting to get the list of the labels without addresses in this case.
_
Thinking that it's possible I'm not getting the meaning of the part of the help explanation which refers to the first and second options ("In combination with the first or second option..."), I've assumed that the first option is the address and the second is the deck, thus I've tried `token balances -w -t fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974 -l`.
The output was the same of `token balances -w -t fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974`, thus the `-l` flag was basically ignored.

Then I've tried `token balances mixcqdAy4aFtuBV7uRebqBTjiFWCcS4UEp -l` (using the address which I interpreted as a first option) and got the following output:
```
{'PoB tokens (default deck)': 61600.0}
```

The `token balances mixcqdAy4aFtuBV7uRebqBTjiFWCcS4UEp -n` output was also not as I'd expect it:
```
{
    'fb93cce7aceb9f7fda228bc0c0c2eca8c56c09c1d846a04bd6a59cae2a895974': 61600.0
}
```
So my question is: what are the first and the second options mentioned in the `token balances` help for the `-k`, `-l` and `-n` flags?
_
I was not able to test the above commands for our default dPoD token deck, because I don't have dPoD tokens on it, which is pity because we'd might be able to track down some other bug there as well.
Wouldn't it be possible to claim the dPod tokens I've got for the older deck in context of our current main deck as well?
Or we should create another proposal and make all the voting and donating rounds to get them again?

**Comment by d5000** [comment]
> token balances -w -n 
> token balances -w -l

Sorry for the confusion, I had added the standard table output (originally the advanced mode was the only one) without modifying the help properly. `-n` only works together with `-a` (advanced mode) and `-t` (single token mode), while `-l` only works with `-a`. The "first and second option" were actually the `-t` and the `-a` mode.

> The token balances mixcqdAy4aFtuBV7uRebqBTjiFWCcS4UEp -n output was also not as I'd expect it:

`-n` refers to address labels, not token labels. This means that combining `-n` with the single _address_ mode makes no sense.

I reworked the help and some messages too (to minimize the usage of the words "deck" and "card"), changed a part which will now ignore the `-n` flag if the table output is chosen and also fixed a bug which showed `(unlabeledX)`-style pseudo labels in some combinations (commit: 9b847fc).

About dPoD tokens: Isn't the `mtFXZtZKndW47L99JooLy42UBXHCwNLvPF` address one of yours? Then you have some units of a valid dPoD token which is `3369f3eb703656c0b46b613dcfb4df78fc05657a0b75f44551634de6321d9d9c` (global name is  `dt_short`). I also sent you tokens of the default dPoD token (`a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a`) to `mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya`, although the tx was unfortunately stuck in my mempool a lot of time, I hope you got them eventually :)

**Comment by buhtignew** [comment]
Everything is clear and works fine now.

The address `mtFXZtZKndW47L99JooLy42UBXHCwNLvPF` isn't mine :-)
I haven't received any dPod token on `mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya` either.

**Comment by d5000** [comment]
>  I haven't received any dPod token on mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya either.
Strange. The token transfer is in transaction b8bd6efd07ced0994fdfffbd11a5bfc8d8db3d9b0ae35d0eb81f6443bb4a7dea, and it is seen as valid by `token transfers -v` on my client (also `pacli token balances -o a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a` shows the 10 dPoD tokens on mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya). Can you confirm that?

**Comment by buhtignew** [comment]
Yes I can confirm that in my `token balances a2459e054ce0f600c90be458915af6bad36a6863a0ce0e33ab76086b514f765a -o` there is the following line:
```
'mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya': 10.0
```
However my `token balances -w | grep mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya` output is:
```
| new_one             | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | 0          | 0           |
```

**Comment by d5000** [comment]
I've looked in the wallet file you provided me some weeks ago and can confirm that you're not seeing them with `token balances -w` nor `address list`. However, `token balances mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya` shows them.

I've looked into it and the wallet doesn't recognize the address as yours, but as dumpprivkey works, it is stored in the wallet.

My conclusion is that we unfortunately again have an unreliable slimcoind command. This time it is `listreceivedbyaddress`, which is used by both `address list` and `token balances`.

To confirm this, can you please enter the following:
`slmtest listreceivedbyaddress 1 true | grep mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya`?

If the result is nothing, then this is the reason. There is a possible workaround at least for `token balances` and `address list`: the command can take into account also all named addresses, regardless if they are from the wallet or not. But in the end it looks that I'll have simply to take into account always that this SLM command is unreliable.

**Comment by buhtignew** [comment]
> slmtest listreceivedbyaddress 1 true | grep mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya

You meant `slimcoind listreceivedbyaddress 1 true | grep mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya` for sure in this case. My output is void.

> or your wallet is again corrupted

I'm not sure my wallet is corrupted, it seems to me that we've solved every issue so far that was connected to its assumed corruption, however it's not difficult to create a new one of course.
I wouldn't have claim transactions on it which would probably make my testing result not that rich as they could've been, but I can switch from one wallet to another to check how the things are functioning in both.

**Comment by buhtignew** [comment]
Suddenly the 10 dPoD tokens you've sent on my `mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya` address has appeared in my ` token balances -w | grep mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya` output:
```
| new_one             | mtmKbmMHdcXXepscuNrwAfjsKLeZzdZdya | 1210.0     | 10.0        |
```
I think it's because the workaround in commit https://github.com/slimcoin-project/pacli/commit/648e9ce99576d0a3316ccb6e78ecb54ce7eedc93 you mentioned earlier.
