### ISSUE TITLE
pobtoken my_burns command

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#96]
I was trying to understand whether I still have some unclaimed PoB tokens and also whether some other dPoD token deck is seeing my donation transactions and would accept them as valid to claim tokens, but I'm not finding the corresponding commands to make this check.
[Here](https://github.com/slimcoin-project/Slimcoin/wiki/PeerAssets:-Proof-of-Burn-tokens-manual#show-your-burn-transactions) I've found the `pacli pobtoken my_burns [--unclaimed] [--wallet] [--deck=DECK]` command but was not able to figure out what it has become with the new wording we've implemented.
Would you please instruct me about?

UPDATE I refer specifically to the `--unclaimed` flag in this case.

**Comment by d5000** [comment]
`pacli transaction list TOKEN -b -w -u`

For example, you'll get the current "official PoB token" unclaimed txes with:

`pacli transaction list ATTokenNewSpec2 -b -w -u`

Just tried it, seems to work fine.

**Comment by buhtignew** [comment]
For the moment I can't test it because of the issue described [here](https://github.com/slimcoin-project/pacli/issues/98#issuecomment-2134510628).

**Comment by d5000** [comment]
I think the problems related to `token list` should be solved, aren't they?

>  Is there any way to see the unclaimed dPoD tokens as well?

Yes, it's `pacli donation list --unclaimed` (or `-u`).

**Comment by buhtignew** [comment]
Yes, this is solved. I'm closing this issue.
