### ISSUE TITLE
Pacli wiki

### ISSUE THREAD

**Issue by buhtignew** [slimcoin-project/pacli#97]
During our testing I've often tried to find the pacli documentation but was not able to. To find it I needed to go to the original reddit posts and use the links that are there.
Finally I've just figured out that our pacli documentation is in the slimcoin wiki. Thus I was wondering whether it would make sense to move it into the pacli project.

**Comment by d5000** [comment]
Yes that makes sense, but the commands are outdated. The manual will be updated once all commands are stable.

**Comment by buhtignew** [comment]
I think we can close this issue unless you'd prefer it to stay open as reminder.
